-- Granting SELECT privilege to group PHOSPHONETX_READONLY

GRANT SELECT ON TABLE EXPERIMENTS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE DATA_SETS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE MODIFICATIONS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE PEPTIDES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE PROTEINS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE SAMPLES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE SEQUENCES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE IDENTIFIED_PROTEINS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE ABUNDANCES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE PROBABILITY_FDR_MAPPINGS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE PROTEIN_REFERENCES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE DATABASES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE MODIFIED_PEPTIDES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE SPECTRUM_REFERENCES TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE MODIFICATION_FRACTIONS TO GROUP PHOSPHONETX_READONLY;
GRANT SELECT ON TABLE EVENTS TO GROUP PHOSPHONETX_READONLY;
