/*
 * Copyright 2015 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.ethz.sis.openbis.generic.server.asapi.v3.translator.entity.sample;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.EntityTypePermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.SampleType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleTypeFetchOptions;
import ch.ethz.sis.openbis.generic.server.asapi.v3.translator.AbstractCachingTranslator;
import ch.ethz.sis.openbis.generic.server.asapi.v3.translator.TranslationContext;
import ch.ethz.sis.openbis.generic.server.asapi.v3.translator.TranslationResults;

/**
 * @author pkupczyk
 */
@Component
public class SampleTypeTranslator extends AbstractCachingTranslator<Long, SampleType, SampleTypeFetchOptions> implements
        ISampleTypeTranslator
{

    @Autowired
    private ISampleTypeBaseTranslator baseTranslator;

    @Override
    protected SampleType createObject(TranslationContext context, Long typeId, SampleTypeFetchOptions fetchOptions)
    {
        final SampleType type = new SampleType();
        type.setFetchOptions(new SampleTypeFetchOptions());
        return type;
    }

    @Override
    protected TranslationResults getObjectsRelations(TranslationContext context, Collection<Long> typeIds, SampleTypeFetchOptions fetchOptions)
    {
        TranslationResults relations = new TranslationResults();

        relations.put(ISampleTypeBaseTranslator.class, baseTranslator.translate(context, typeIds, null));

        return relations;
    }

    @Override
    protected void updateObject(TranslationContext context, Long typeId, SampleType result, Object objectRelations,
            SampleTypeFetchOptions fetchOptions)
    {
        TranslationResults relations = (TranslationResults) objectRelations;
        SampleTypeBaseRecord baseRecord = relations.get(ISampleTypeBaseTranslator.class, typeId);

        result.setPermId(new EntityTypePermId(baseRecord.code));
        result.setCode(baseRecord.code);
        result.setDescription(baseRecord.description);
        result.setAutoGeneratedCode(baseRecord.autoGeneratedCode);
        result.setGeneratedCodePrefix(baseRecord.generatedCodePrefix);
        result.setListable(baseRecord.listable);
        result.setShowParentMetadata(baseRecord.showParentMetadata);
        result.setSubcodeUnique(baseRecord.subcodeUnique);
        result.setModificationDate(baseRecord.modificationDate);
    }

}
