/*
Created: 06/05/2009
Modified: 20/05/2009
Model: Proteomics
Database: PostgreSQL 8.2
*/

-- Create domain types section -------------------------------------------------

CREATE DOMAIN BINARY_DATA AS Bytea
;

CREATE DOMAIN CHECKSUM AS Character varying(8)
;

CREATE DOMAIN CODE AS Character varying(40)
;

CREATE DOMAIN INTEGER_NUMBER AS Integer
;

CREATE DOMAIN REAL_NUMBER AS Double precision
;

CREATE DOMAIN SEQUENCE AS Text
;

CREATE DOMAIN SHORT_DESCRIPTION AS Character varying(200)
;

CREATE DOMAIN TECH_ID AS Bigint
;

-- Create tables section -------------------------------------------------

-- Table ABUNDANCES

CREATE TABLE ABUNDANCES(
 ID TECH_ID NOT NULL,
 ABTY_ID TECH_ID NOT NULL,
 AMOUNT REAL_NUMBER NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table ABUNDANCES

ALTER TABLE ABUNDANCES ADD CONSTRAINT ABUN_PK PRIMARY KEY (ID)
;

-- Table ABUNDANCES_TYPES

CREATE TABLE ABUNDANCES_TYPES(
 ID TECH_ID NOT NULL,
 CODE CODE NOT NULL,
 DESCRIPTION SHORT_DESCRIPTION
)
WITH (OIDS=FALSE)
;

-- Add keys for table ABUNDANCES_TYPES

ALTER TABLE ABUNDANCES_TYPES ADD CONSTRAINT ABTY_PK PRIMARY KEY (ID)
;

ALTER TABLE ABUNDANCES_TYPES ADD CONSTRAINT ABTY_CODE_BK UNIQUE (CODE)
;

-- Table IDENTIFICATION_DATA

CREATE TABLE IDENTIFICATION_DATA(
 ID TECH_ID NOT NULL,
 SPEC_ID TECH_ID,
 SPECTRA_COUNT INTEGER_NUMBER
)
WITH (OIDS=FALSE)
;

ALTER TABLE IDENTIFICATION_DATA ADD CONSTRAINT IDDA_PK PRIMARY KEY (ID)
;

-- Table MODIFICATIONS

CREATE TABLE MODIFICATIONS(
 ID TECH_ID NOT NULL,
 MOPE_ID TECH_ID NOT NULL,
 MOTY_ID TECH_ID NOT NULL,
 POSITION INTEGER_NUMBER NOT NULL,
 MASS REAL_NUMBER NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table MODIFICATIONS

ALTER TABLE MODIFICATIONS ADD CONSTRAINT MODI_PK PRIMARY KEY (ID)
;

-- Table MODIFICATION_TYPES

CREATE TABLE MODIFICATION_TYPES(
 ID TECH_ID NOT NULL,
 CODE CODE NOT NULL,
 DESCRIPTION SHORT_DESCRIPTION,
 MASS REAL_NUMBER,
 DELTA_MASS REAL_NUMBER
)
WITH (OIDS=FALSE)
;

-- Add keys for table MODIFICATION_TYPES

ALTER TABLE MODIFICATION_TYPES ADD CONSTRAINT MOTY_PK PRIMARY KEY (ID)
;

ALTER TABLE MODIFICATION_TYPES ADD CONSTRAINT MOTY_CODE_BK UNIQUE (CODE)
;

-- Table MODIFIED_PEPTIDES

CREATE TABLE MODIFIED_PEPTIDES(
 ID TECH_ID NOT NULL,
 PEPT_ID TECH_ID NOT NULL,
 ABUN_ID TECH_ID,
 IDDA_ID TECH_ID,
 CHARGE INTEGER_NUMBER NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table MODIFIED_PEPTIDES

ALTER TABLE MODIFIED_PEPTIDES ADD CONSTRAINT MOPE_PK PRIMARY KEY (ID)
;

-- Table PEPTIDES

CREATE TABLE PEPTIDES(
 ID TECH_ID NOT NULL,
 PROT_ID TECH_ID NOT NULL,
 SEQU_ID TECH_ID NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table PEPTIDES

ALTER TABLE PEPTIDES ADD CONSTRAINT PEPT_PK PRIMARY KEY (ID)
;

-- Table PROTEIN_STATISTICS

CREATE TABLE PROTEIN_STATISTICS(
 ID TECH_ID NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table PROTEIN_STATISTICS

ALTER TABLE PROTEIN_STATISTICS ADD CONSTRAINT PRST_PK PRIMARY KEY (ID)
;

-- Table PROTEINS

CREATE TABLE PROTEINS(
 ID TECH_ID NOT NULL,
 SEQU_ID TECH_ID NOT NULL,
 ABUN_ID TECH_ID,
 PRST_ID TECH_ID
)
WITH (OIDS=FALSE)
;

-- Add keys for table PROTEINS

ALTER TABLE PROTEINS ADD CONSTRAINT PROT_PK PRIMARY KEY (ID)
;

-- Table SEQUENCES

CREATE TABLE SEQUENCES(
 ID TECH_ID NOT NULL,
 AMINO_ACID_SEQUENCE SEQUENCE NOT NULL,
 CHECKSUM CHECKSUM NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table SEQUENCES

ALTER TABLE SEQUENCES ADD CONSTRAINT SEQU_PK PRIMARY KEY (ID)
;

-- Table SPECTRA

CREATE TABLE SPECTRA(
 ID TECH_ID NOT NULL,
 DATA BINARY_DATA NOT NULL
)
WITH (OIDS=FALSE)
;

-- Add keys for table SPECTRA

ALTER TABLE SPECTRA ADD CONSTRAINT SPEC_PK PRIMARY KEY (ID)
;

-- Create relationships section ------------------------------------------------- 

CREATE INDEX IX_PE_PR_FK_PEPTIDES ON PEPTIDES (PROT_ID)
;
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_PR_FK FOREIGN KEY (PROT_ID) REFERENCES PROTEINS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_PE_SE_FK_PEPTIDES ON PEPTIDES (SEQU_ID)
;
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_SE_FK FOREIGN KEY (SEQU_ID) REFERENCES SEQUENCES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_PR_SE_FK_PROTEINS ON PROTEINS (SEQU_ID)
;
ALTER TABLE PROTEINS ADD CONSTRAINT PR_SE_FK FOREIGN KEY (SEQU_ID) REFERENCES SEQUENCES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_MO_PE_FK_MODIFIED_PEPTIDES ON MODIFIED_PEPTIDES (PEPT_ID)
;
ALTER TABLE MODIFIED_PEPTIDES ADD CONSTRAINT MO_PE_FK FOREIGN KEY (PEPT_ID) REFERENCES PEPTIDES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_MO_MP_FK_MODIFICATIONS ON MODIFICATIONS (MOPE_ID)
;
ALTER TABLE MODIFICATIONS ADD CONSTRAINT MO_MP_FK FOREIGN KEY (MOPE_ID) REFERENCES MODIFIED_PEPTIDES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_MO_MT_FK_MODIFICATIONS ON MODIFICATIONS (MOTY_ID)
;
ALTER TABLE MODIFICATIONS ADD CONSTRAINT MO_MT_FK FOREIGN KEY (MOTY_ID) REFERENCES MODIFICATION_TYPES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_AB_AT_FK_ABUNDANCES ON ABUNDANCES (ABTY_ID)
;
ALTER TABLE ABUNDANCES ADD CONSTRAINT AB_AT_FK FOREIGN KEY (ABTY_ID) REFERENCES ABUNDANCES_TYPES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_PR_AB_FK_PROTEINS ON PROTEINS (ABUN_ID)
;
ALTER TABLE PROTEINS ADD CONSTRAINT PR_AB_FK FOREIGN KEY (ABUN_ID) REFERENCES ABUNDANCES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_MP_AB_FK_MODIFIED_PEPTIDES ON MODIFIED_PEPTIDES (ABUN_ID)
;
ALTER TABLE MODIFIED_PEPTIDES ADD CONSTRAINT MP_AB_FK FOREIGN KEY (ABUN_ID) REFERENCES ABUNDANCES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_PR_PS_FK_PROTEINS ON PROTEINS (PRST_ID)
;
ALTER TABLE PROTEINS ADD CONSTRAINT PR_PS_FK FOREIGN KEY (PRST_ID) REFERENCES PROTEIN_STATISTICS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_MO_ID_FK_MODIFIED_PEPTIDES ON MODIFIED_PEPTIDES (IDDA_ID)
;
ALTER TABLE MODIFIED_PEPTIDES ADD CONSTRAINT MO_ID_FK FOREIGN KEY (IDDA_ID) REFERENCES IDENTIFICATION_DATA (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

CREATE INDEX IX_ID_SP_FK_IDENTIFICATION_DATA ON IDENTIFICATION_DATA (SPEC_ID)
;
ALTER TABLE IDENTIFICATION_DATA ADD CONSTRAINT ID_SP_FK FOREIGN KEY (SPEC_ID) REFERENCES SPECTRA (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;


