/*
 * Copyright 2009 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

-- Create domain types -------------------------------------------------

CREATE DOMAIN ACCESSION_NUMBER AS Character varying(400);

CREATE DOMAIN BINARY_DATA AS Bytea;

CREATE DOMAIN CHECKSUM AS Character varying(8);

CREATE DOMAIN CODE AS Character varying(40);

CREATE DOMAIN DESCRIPTION AS Character varying(2000);

CREATE DOMAIN INTEGER_NUMBER AS Integer;

CREATE DOMAIN REAL_NUMBER AS Double precision;

CREATE DOMAIN SEQUENCE AS Text;

CREATE DOMAIN SHORT_DESCRIPTION AS Character varying(200);

CREATE DOMAIN TECH_ID AS BIGINT;

-- Create tables -------------------------------------------------

-- Table ABUNDANCES

CREATE TABLE ABUNDANCES(
  ID BIGSERIAL NOT NULL,
  ABTY_ID TECH_ID NOT NULL,
  AMOUNT REAL_NUMBER NOT NULL,
  PRIMARY KEY (ID)
);

-- Table ABUNDANCES_TYPES

CREATE TABLE ABUNDANCES_TYPES(
  ID BIGSERIAL NOT NULL,
  CODE CODE NOT NULL,
  DESCRIPTION SHORT_DESCRIPTION,
  PRIMARY KEY (ID),
  UNIQUE (CODE)
);

-- Table ANNOTATIONS

CREATE TABLE ANNOTATIONS(
  ID BIGSERIAL NOT NULL,
  PROT_ID TECH_ID NOT NULL,
  PROTEIN_DESCRIPTION DESCRIPTION NOT NULL,
  IPI_NAME ACCESSION_NUMBER,
  REFSEQ_NAME ACCESSION_NUMBER,
  SWISSPROT_NAME ACCESSION_NUMBER,
  ENSEMBL_NAME ACCESSION_NUMBER,
  TREMBL_NAME ACCESSION_NUMBER,
  LOCUS_LINK_NAME ACCESSION_NUMBER,
  FLYBASE ACCESSION_NUMBER,
  PRIMARY KEY (ID)
);

-- Table EXPERIMENTS

CREATE TABLE EXPERIMENTS(
  ID BIGSERIAL NOT NULL,
  PERM_ID CODE NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (PERM_ID)
);

-- Table DATA_SETS

CREATE TABLE DATA_SETS(
  ID BIGSERIAL NOT NULL,
  PERM_ID CODE NOT NULL,  
  EXPE_ID TECH_ID NOT NULL,
  SAMP_ID TECH_ID,
  PRIMARY KEY (ID),
  UNIQUE (PERM_ID)
);

-- Table IDENTIFICATION_DATA

CREATE TABLE IDENTIFICATION_DATA(
  ID BIGSERIAL NOT NULL,
  SPEC_ID TECH_ID,
  SPECTRA_COUNT INTEGER_NUMBER,
  PRIMARY KEY (ID)
);

-- Table MODIFICATIONS

CREATE TABLE MODIFICATIONS(
  ID BIGSERIAL NOT NULL,
  PEPT_ID TECH_ID NOT NULL,
  MOTY_ID TECH_ID NOT NULL,
  POSITION INTEGER_NUMBER NOT NULL,
  MASS REAL_NUMBER NOT NULL,
  PRIMARY KEY (ID)
);

-- Table MODIFICATION_TYPES

CREATE TABLE MODIFICATION_TYPES(
  ID BIGSERIAL NOT NULL,
  CODE CODE NOT NULL,
  DESCRIPTION SHORT_DESCRIPTION,
  MASS REAL_NUMBER,
  DELTA_MASS REAL_NUMBER,
  PRIMARY KEY (ID),
  UNIQUE (CODE)
);

-- Table PEPTIDES

CREATE TABLE PEPTIDES(
  ID BIGSERIAL NOT NULL,
  PROT_ID TECH_ID NOT NULL,
  SEQU_ID TECH_ID NOT NULL,
  ABUN_ID TECH_ID,
  IDDA_ID TECH_ID,
  CHARGE INTEGER_NUMBER NOT NULL,
  PRIMARY KEY (ID)
);

-- Table PROTEIN_STATISTICS

CREATE TABLE PROTEIN_STATISTICS(
  ID BIGSERIAL NOT NULL,
  PRIMARY KEY (ID)
);

-- Table PROTEINS

CREATE TABLE PROTEINS(
  ID BIGSERIAL NOT NULL,
  DASE_ID TECH_ID NOT NULL,
  ABUN_ID TECH_ID,
  SEQU_ID TECH_ID,
  PRST_ID TECH_ID,
  PRIMARY KEY (ID)
);

-- Table SAMPLES

CREATE TABLE SAMPLES(
  ID BIGSERIAL NOT NULL,
  PERM_ID CODE NOT NULL,
  EXPE_ID TECH_ID NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (PERM_ID)
);

-- Table SEQUENCES

CREATE TABLE SEQUENCES(
  ID BIGSERIAL NOT NULL,
  AMINO_ACID_SEQUENCE SEQUENCE NOT NULL,
  CHECKSUM CHECKSUM NOT NULL,
  PRIMARY KEY (ID)
);

-- Table SPECTRA

CREATE TABLE SPECTRA(
  ID BIGSERIAL NOT NULL,
  DATA BINARY_DATA NOT NULL,
  PRIMARY KEY (ID)
);


-- Create relationships ------------------------------------------------- 

CREATE INDEX IX_FK_ABUNDANCES_ABUNDANCES_TYPES ON ABUNDANCES (ABTY_ID);
ALTER TABLE ABUNDANCES ADD CONSTRAINT AB_AT_FK FOREIGN KEY (ABTY_ID) REFERENCES ABUNDANCES_TYPES (ID);

CREATE INDEX IX_FK_ANNOTATIONS_PROTEINS ON ANNOTATIONS (PROT_ID);
ALTER TABLE ANNOTATIONS ADD CONSTRAINT AN_PR_FK FOREIGN KEY (PROT_ID) REFERENCES PROTEINS (ID);

CREATE INDEX IX_FK_DATA_SETS_EXPERIMENTS ON DATA_SETS (EXPE_ID);
ALTER TABLE DATA_SETS ADD CONSTRAINT DA_EX_FK FOREIGN KEY (EXPE_ID) REFERENCES EXPERIMENTS (ID);

CREATE INDEX IX_FK_DATA_SETS_SAMPLES ON DATA_SETS (SAMP_ID);
ALTER TABLE DATA_SETS ADD CONSTRAINT DA_SA_FK FOREIGN KEY (SAMP_ID) REFERENCES SAMPLES (ID);

CREATE INDEX IX_FK_IDENTIFICATION_DATA_SPECTRA ON IDENTIFICATION_DATA (SPEC_ID);
ALTER TABLE IDENTIFICATION_DATA ADD CONSTRAINT ID_SP_FK FOREIGN KEY (SPEC_ID) REFERENCES SPECTRA (ID);

CREATE INDEX IX_FK_MODIFICATIONS_PEPTIDES ON MODIFICATIONS (PEPT_ID);
ALTER TABLE MODIFICATIONS ADD CONSTRAINT MO_PE_FK FOREIGN KEY (PEPT_ID) REFERENCES PEPTIDES (ID);

CREATE INDEX IX_FK_MODIFICATIONS_MODIFICATION_TYPES ON MODIFICATIONS (MOTY_ID);
ALTER TABLE MODIFICATIONS ADD CONSTRAINT MO_MT_FK FOREIGN KEY (MOTY_ID) REFERENCES MODIFICATION_TYPES (ID);

CREATE INDEX IX_FK_PEPTIDES_ABUNDANCES ON PEPTIDES (ABUN_ID);
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_AB_FK FOREIGN KEY (ABUN_ID) REFERENCES ABUNDANCES (ID);

CREATE INDEX IX_FK_PEPTIDES_IDENTIFICATION_DATA ON PEPTIDES (IDDA_ID);
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_ID_FK FOREIGN KEY (IDDA_ID) REFERENCES IDENTIFICATION_DATA (ID);

CREATE INDEX IX_FK_PEPTIDES_PROTEINS ON PEPTIDES (PROT_ID);
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_PR_FK FOREIGN KEY (PROT_ID) REFERENCES PROTEINS (ID);

CREATE INDEX IX_FK_PEPTIDES_SEQUENCES ON PEPTIDES (SEQU_ID);
ALTER TABLE PEPTIDES ADD CONSTRAINT PE_SE_FK FOREIGN KEY (SEQU_ID) REFERENCES SEQUENCES (ID);

CREATE INDEX IX_FK_PROTEINS_DATA_SETS ON PROTEINS (DASE_ID);
ALTER TABLE PROTEINS ADD CONSTRAINT PR_DA_FK FOREIGN KEY (DASE_ID) REFERENCES DATA_SETS (ID);

CREATE INDEX IX_FK_PROTEINS_SEQUENCES ON PROTEINS (SEQU_ID);
ALTER TABLE PROTEINS ADD CONSTRAINT PR_SE_FK FOREIGN KEY (SEQU_ID) REFERENCES SEQUENCES (ID);

CREATE INDEX IX_FK_PROTEINS_ABUNDANCES ON PROTEINS (ABUN_ID);
ALTER TABLE PROTEINS ADD CONSTRAINT PR_AB_FK FOREIGN KEY (ABUN_ID) REFERENCES ABUNDANCES (ID);

CREATE INDEX IX_FK_PROTEINS_PROTEIN_STATISTICS ON PROTEINS (PRST_ID);
ALTER TABLE PROTEINS ADD CONSTRAINT PR_PS_FK FOREIGN KEY (PRST_ID) REFERENCES PROTEIN_STATISTICS (ID);


