-- Migration from 018 to 019

ALTER TABLE IMAGE_ZOOM_LEVELS ADD COLUMN PATH FILE_PATH;
ALTER TABLE IMAGE_ZOOM_LEVELS ADD COLUMN  WIDTH INTEGER;
ALTER TABLE IMAGE_ZOOM_LEVELS ADD COLUMN  HEIGHT INTEGER;