package ch.ethz.sis.openbis.generic.shared.api.v3.dto.generators;

import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.List;

import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.attachment.Attachment;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.experiment.ExperimentType;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.person.Person;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.project.Project;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.sample.Sample;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.entity.sample.SampleType;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.EmptyFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.attachment.AttachmentFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.dataset.DataSetFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.experiment.ExperimentFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.experiment.ExperimentTypeFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.person.PersonFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.project.ProjectFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.sample.SampleFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.sample.SampleTypeFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.space.SpaceFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.fetchoptions.tag.TagFetchOptions;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.entitytype.EntityTypePermId;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.experiment.ExperimentIdentifier;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.experiment.ExperimentPermId;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.project.ProjectIdentifier;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.project.ProjectPermId;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.sample.SampleIdentifier;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.sample.SamplePermId;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.space.SpacePermId;
import ch.ethz.sis.openbis.generic.shared.api.v3.dto.id.tag.TagPermId;

public class Generator extends AbstractGenerator
{

    private static DtoGenerator createSampleGenerator()
    {
        DtoGenerator gen = new DtoGenerator("sample", "Sample", SampleFetchOptions.class);

        gen.addSimpleField(SamplePermId.class, "permId");
        gen.addSimpleField(SampleIdentifier.class, "identifier");
        addCode(gen);
        addRegistrationDate(gen);
        addModificationDate(gen);

        gen.addFetchedField(SampleType.class, "sampleType", "Sample type", SampleTypeFetchOptions.class);
        addSpace(gen);
        addExperiment(gen);
        addProperties(gen);
        gen.addFetchedField("List<Sample>", List.class.getName(), "parents", "Parents", SampleFetchOptions.class);
        gen.addFetchedField("List<Sample>", List.class.getName(), "children", "Children", SampleFetchOptions.class);
        gen.addFetchedField(Sample.class, "container", "Container sample", SampleFetchOptions.class);
        gen.addFetchedField("List<Sample>", List.class.getName(), "contained", "Contained samples", SampleFetchOptions.class);
        addTags(gen);
        addRegistrator(gen);
        addModifier(gen);
        addAttachments(gen);

        gen.setToStringMethod("\"Sample \" + permId");

        return gen;
    }

    private static DtoGenerator createSampleTypeGenerator()
    {
        // type.getContainerHierarchyDepth();
        // type.getGeneratedFromHierarchyDepth();
        // the two fields are ignored as they are hints for old api translations

        // potentially missing fields:

        // type.getSampleTypePropertyTypes();
        // type.getValidationScript();

        DtoGenerator gen = new DtoGenerator("sample", "SampleType", SampleTypeFetchOptions.class);

        gen.addSimpleField(EntityTypePermId.class, "permId");
        addCode(gen);
        addDescription(gen);
        gen.addSimpleField(Boolean.class, "listable");
        gen.addSimpleField(Boolean.class, "subcodeUnique");
        gen.addSimpleField(Boolean.class, "autoGeneratedCode");
        gen.addSimpleField(Boolean.class, "showParentMetadata");

        gen.addSimpleField(String.class, "generatedCodePrefix");
        addModificationDate(gen);

        return gen;
    }

    private static DtoGenerator createAttachmentGenerator()
    {
        DtoGenerator gen = new DtoGenerator("attachment", "Attachment", AttachmentFetchOptions.class);

        gen.addSimpleField(String.class, "fileName");
        gen.addSimpleField(String.class, "title");
        addDescription(gen);
        gen.addSimpleField(String.class, "permlink");
        gen.addSimpleField(String.class, "latestVersionPermlink");
        gen.addSimpleField(Integer.class, "version");
        addRegistrationDate(gen);

        addRegistrator(gen);
        gen.addFetchedField(Attachment.class, "previousVersion", "Previous version of attachment ", AttachmentFetchOptions.class);

        gen.addFetchedField(byte[].class, "content", "Content", EmptyFetchOptions.class);

        gen.setToStringMethod("\"Attachment \" + fileName + \":\" + version");

        return gen;
    }

    private static DtoGenerator createExperimentGenerator()
    {
        DtoGenerator gen = new DtoGenerator("experiment", "Experiment", ExperimentFetchOptions.class);

        gen.addSimpleField(ExperimentPermId.class, "permId");
        gen.addSimpleField(ExperimentIdentifier.class, "identifier");
        addCode(gen);
        addRegistrationDate(gen);
        addModificationDate(gen);

        gen.addFetchedField(ExperimentType.class, "type", "Experiment type", ExperimentTypeFetchOptions.class);
        gen.addFetchedField(Project.class, "project", "Project", ProjectFetchOptions.class);
        addProperties(gen);
        addTags(gen);
        addRegistrator(gen);
        addModifier(gen);
        addAttachments(gen);

        gen.setToStringMethod("\"Experiment \" + permId");

        return gen;
    }

    private static DtoGenerator createExperimentTypeGenerator()
    {
        DtoGenerator gen = new DtoGenerator("experiment", "ExperimentType", ExperimentTypeFetchOptions.class);

        gen.addSimpleField(EntityTypePermId.class, "permId");
        addCode(gen);
        addDescription(gen);
        addModificationDate(gen);

        // TODO add property definitions

        // TODO add validation script
        return gen;
    }

    private static DtoGenerator createDatasetGenerator()
    {
        DtoGenerator gen = new DtoGenerator("dataset", "DataSet", DataSetFetchOptions.class);
        return gen;
    }

    private static DtoGenerator createPersonGenerator()
    {
        DtoGenerator gen = new DtoGenerator("person", "Person", PersonFetchOptions.class);

        gen.addSimpleField(String.class, "userId");
        gen.addSimpleField(String.class, "firstName");
        gen.addSimpleField(String.class, "lastName");
        gen.addSimpleField(String.class, "email");
        addRegistrationDate(gen);
        gen.addSimpleField(Boolean.class, "active");

        addSpace(gen);
        addRegistrator(gen);

        return gen;
    }

    private static DtoGenerator createProjectGenerator()
    {
        DtoGenerator gen = new DtoGenerator("project", "Project", ProjectFetchOptions.class);

        gen.addSimpleField(ProjectPermId.class, "permId");
        gen.addSimpleField(ProjectIdentifier.class, "identifier");
        addCode(gen);
        addDescription(gen);
        addRegistrationDate(gen);
        addModificationDate(gen);

        addSpace(gen);
        addRegistrator(gen);
        addModifier(gen);

        return gen;
    }

    private static DtoGenerator createSpaceGenerator()
    {
        DtoGenerator gen = new DtoGenerator("space", "Space", SpaceFetchOptions.class);

        gen.addSimpleField(SpacePermId.class, "permId");
        addCode(gen);
        addDescription(gen);
        addRegistrationDate(gen);

        addRegistrator(gen);

        return gen;
    }
    
    private static DtoGenerator createTagGenerator()
    {
        DtoGenerator gen = new DtoGenerator("tag", "Tag", TagFetchOptions.class);
        
        gen.addSimpleField(TagPermId.class, "permId");
        gen.addSimpleField(String.class, "name");
        addDescription(gen);
        gen.addSimpleField(Boolean.class, "private", "isPrivate");
        addRegistrationDate(gen);
        
        gen.addFetchedField(Person.class, "owner", "Owner", PersonFetchOptions.class);

        return gen;
    }

    public static void main(String[] args) throws FileNotFoundException
    {
        List<DtoGenerator> list = new LinkedList<DtoGenerator>();
        list.add(createDatasetGenerator());
        list.add(createAttachmentGenerator());
        list.add(createExperimentGenerator());
        list.add(createExperimentTypeGenerator());
        list.add(createPersonGenerator());
        list.add(createProjectGenerator());
        list.add(createSampleGenerator());
        list.add(createSampleTypeGenerator());
        list.add(createSpaceGenerator());
        list.add(createTagGenerator());

        for (DtoGenerator gen : list)
        {
            System.out.print("Generating api classes for " + gen + "...");
            gen.generateDTO();
            gen.generateFetchOptions();
            System.out.println("done");
        }
    }
}
