/*
 * Copyright 2010 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.cina.client.util.cli;

import org.jmock.Expectations;
import org.jmock.Mockery;
import org.testng.AssertJUnit;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import ch.systemsx.cisd.cina.client.util.v1.ICinaUtilities;
import ch.systemsx.cisd.openbis.dss.client.api.cli.ICommand;
import ch.systemsx.cisd.openbis.generic.shared.IETLLIMSService;
import ch.systemsx.cisd.openbis.generic.shared.api.v1.IGeneralInformationService;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.SampleType;

/**
 * @author Chandrasekhar Ramakrishnan
 */
public class CommandGenerateSampleCodeTest extends AssertJUnit
{
    private final class MockCommandGenerateSampleCode extends CommandGenerateSampleCode
    {

        @Override
        protected ICinaUtilities login()
        {
            facade =
                    ch.systemsx.cisd.cina.client.util.v1.impl.CinaUtilitiesFacadeTest.createFacade(
                            service, openbisService, USER_ID, PASSWORD);
            return facade;
        }

    }

    private final static String USER_ID = "userid";

    private final static String PASSWORD = "password";

    private final static String SESSION_TOKEN = "sessionToken";

    private Mockery context;

    private ICinaUtilities facade;

    private IGeneralInformationService service;

    private IETLLIMSService openbisService;

    @BeforeMethod
    public void setUp()
    {
        context = new Mockery();
        service = context.mock(IGeneralInformationService.class);
        openbisService = context.mock(IETLLIMSService.class);
    }

    @AfterMethod
    public void tearDown()
    {
        // To following line of code should also be called at the end of each test method.
        // Otherwise one does not known which test failed.
        context.assertIsSatisfied();
    }

    @Test
    public void testCodePath()
    {
        final String sampleTypeCode = "SampleTypeCode";
        final SampleType sampleType = new SampleType();
        sampleType.setAutoGeneratedCode(true);
        sampleType.setGeneratedCodePrefix("STC-");
        context.checking(new Expectations()
            {
                {
                    one(service).tryToAuthenticateForAllServices(USER_ID, PASSWORD);
                    will(returnValue(SESSION_TOKEN));

                    one(openbisService).getSampleType(SESSION_TOKEN, sampleTypeCode.toUpperCase());
                    will(returnValue(sampleType));

                    one(openbisService).drawANewUniqueID(SESSION_TOKEN);
                    will(returnValue((long) 1));

                    one(service).logout(SESSION_TOKEN);
                }
            });
        ICommand command = new MockCommandGenerateSampleCode();

        int exitCode = command.execute(new String[]
            { "-s", "url", "-u", USER_ID, "-p", PASSWORD, sampleTypeCode });

        assertEquals(0, exitCode);
        context.assertIsSatisfied();
    }

    @Test
    public void testMissingArguments()
    {
        context.checking(new Expectations()
            {
                {

                }
            });
        ICommand command = new MockCommandGenerateSampleCode();

        int exitCode = command.execute(new String[]
            { "-s", "url", "-u", USER_ID, "-p", PASSWORD });

        assertEquals(1, exitCode);
        context.assertIsSatisfied();
    }
}
