#!/bin/bash
cd Data
echo Checksumming Lane 1
find . -type f | grep -Ev '/s_[2345678][^/]*$' | xargs md5sum >s_1.md5 
echo Checksumming Lane 2
find . -type f | grep -Ev '/s_[1345678][^/]*$' | xargs md5sum >s_2.md5 
echo Checksumming Lane 3
find . -type f | grep -Ev '/s_[1245678][^/]*$' | xargs md5sum >s_3.md5 
echo Checksumming Lane 4
find . -type f | grep -Ev '/s_[1235678][^/]*$' | xargs md5sum >s_4.md5 
echo Checksumming Lane 5
find . -type f | grep -Ev '/s_[1234678][^/]*$' | xargs md5sum >s_5.md5 
echo Checksumming Lane 6
find . -type f | grep -Ev '/s_[1234578][^/]*$' | xargs md5sum >s_6.md5 
echo Checksumming Lane 7
find . -type f | grep -Ev '/s_[1234568][^/]*$' | xargs md5sum >s_7.md5 
echo Checksumming Lane 8
find . -type f | grep -Ev '/s_[1234567][^/]*$' | xargs md5sum >s_8.md5 