/*
 * Copyright 2010 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.dss.etl.dataaccess;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * @author Tomasz Pylak
 */
public class ImgChannelStackDTO
{
    @AutoGeneratedKeys
    private long id;

    // x and y are kind of a two dimensional sequence number, (e.g. tile column)
    @ResultColumn("X")
    private Integer x;

    // x and y are kind of a two dimensional sequence number, (e.g. tile row, 1 is the first row)
    // Some use case may only use x and leave y alone.
    @ResultColumn("Y")
    private Integer y;

    // can be null
    @ResultColumn("Z_in_M")
    private Float z;

    // can be null
    @ResultColumn("T_in_SEC")
    private Float t;

    @ResultColumn("DS_ID")
    private long datasetId;

    @ResultColumn("SPOT_ID")
    private long spotId;

    public ImgChannelStackDTO(int x, int y, long datasetId, long spotId)
    {
        this.x = x;
        this.y = y;
        this.datasetId = datasetId;
        this.spotId = spotId;
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public Integer getX()
    {
        return x;
    }

    public void setX(Integer x)
    {
        this.x = x;
    }

    public Integer getY()
    {
        return y;
    }

    public void setY(Integer y)
    {
        this.y = y;
    }

    public Float getZ()
    {
        return z;
    }

    public void setZ(Float z)
    {
        this.z = z;
    }

    public Float getT()
    {
        return t;
    }

    public void setT(Float t)
    {
        this.t = t;
    }

    public long getDatasetId()
    {
        return datasetId;
    }

    public void setDatasetId(long datasetId)
    {
        this.datasetId = datasetId;
    }

    public long getSpotId()
    {
        return spotId;
    }

    public void setSpotId(long spotId)
    {
        this.spotId = spotId;
    }

}
