/*
 * Copyright 2010 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.dss.etl.dataaccess;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * DTO holding information about the container in the imaging database.
 * 
 * @author Tomasz Pylak
 */
public class ImgContainerDTO
{
    @AutoGeneratedKeys
    private long id;

    @ResultColumn("PERM_ID")
    private String permId;

    @ResultColumn("SPOTS_WIDTH")
    private Integer spotWidth;

    @ResultColumn("SPOTS_HEIGHT")
    private Integer spotHeight;

    @ResultColumn("EXPE_ID")
    private long experimentId;

    @SuppressWarnings("unused")
    private ImgContainerDTO()
    {
    }

    public ImgContainerDTO(String permId, Integer spotWidth, Integer spotHeight, long experimentId)
    {
        this.permId = permId;
        this.spotWidth = spotWidth;
        this.spotHeight = spotHeight;
        this.experimentId = experimentId;
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getPermId()
    {
        return permId;
    }

    public void setPermId(String permId)
    {
        this.permId = permId;
    }

    public Integer getSpotWidth()
    {
        return spotWidth;
    }

    public void setSpotWidth(Integer spotWidth)
    {
        this.spotWidth = spotWidth;
    }

    public Integer getSpotHeight()
    {
        return spotHeight;
    }

    public void setSpotHeight(Integer spotHeight)
    {
        this.spotHeight = spotHeight;
    }

    public long getExperimentId()
    {
        return experimentId;
    }

    public void setExperimentId(long experimentId)
    {
        this.experimentId = experimentId;
    }

}
