/*
 * Copyright 2010 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.dss.etl.dataaccess;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * @author Tomasz Pylak
 */
public class ImgImageDTO
{
    @AutoGeneratedKeys
    private long id;

    @ResultColumn("PATH")
    private String filePath;

    @ResultColumn("PAGE")
    private Integer pathOrNull;

    @ResultColumn("COLOR")
    private ColorComponent colorComponentOrNull;

    public static enum ColorComponent
    {
        RED, GREEN, BLUE
    }

    public ImgImageDTO(String filePath)
    {
        this(filePath, null, null);
    }

    public ImgImageDTO(String filePath, Integer pathOrNull, ColorComponent colorComponentOrNull)
    {
        this.filePath = filePath;
        this.pathOrNull = pathOrNull;
        this.colorComponentOrNull = colorComponentOrNull;
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getFilePath()
    {
        return filePath;
    }

    public void setFilePath(String filePath)
    {
        this.filePath = filePath;
    }

    public Integer getPath()
    {
        return pathOrNull;
    }

    public void setPath(Integer path)
    {
        this.pathOrNull = path;
    }

    public ColorComponent getColorComponent()
    {
        return colorComponentOrNull;
    }

    public void setColorComponent(ColorComponent colorComponent)
    {
        this.colorComponentOrNull = colorComponent;
    }

}
