/*
 * Copyright 2010 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.dss.etl.dataaccess;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * @author Tomasz Pylak
 */
public class ImgSpotDTO
{
    @AutoGeneratedKeys
    private long id;

    @ResultColumn("PERM_ID")
    private String permId;

    // position in the container, one-based (e.g. well column)
    @ResultColumn("X")
    private Integer x;

    // position in the container, one-based (e.g. well row, 1 is the first row)
    @ResultColumn("Y")
    private Integer y;

    @ResultColumn("CONT_ID")
    private long containerId;

    @SuppressWarnings("unused")
    private ImgSpotDTO()
    {
        // All Data-Object classes must have a default constructor.
    }

    public ImgSpotDTO(String permId, Integer x, Integer y, long containerId)
    {
        this.permId = permId;
        this.x = x;
        this.y = y;
        this.containerId = containerId;
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public String getPermId()
    {
        return permId;
    }

    public void setPermId(String permId)
    {
        this.permId = permId;
    }

    public Integer getX()
    {
        return x;
    }

    public void setX(Integer x)
    {
        this.x = x;
    }

    public Integer getY()
    {
        return y;
    }

    public void setY(Integer y)
    {
        this.y = y;
    }

    public long getContainerId()
    {
        return containerId;
    }

    public void setContainerId(long containerId)
    {
        this.containerId = containerId;
    }

}
