-- Disabling triggers

-- Samples

ALTER TABLE samples_all
    DISABLE TRIGGER MELT_SAMPLE_FOR,
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_TRASH,
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_DELETE,
    DISABLE TRIGGER ADD_SAMPLE_TO_CONTAINER_CHECK,
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_SET_CONTAINER,
    DISABLE TRIGGER ADD_SAMPLE_TO_EXPERIMENT_CHECK,
    DISABLE TRIGGER SAMPLE_EXPERIMENT_RELATIONSHIP_FROZEN_CHECK,
    DISABLE TRIGGER ADD_SAMPLE_TO_PROJECT_CHECK,
    DISABLE TRIGGER SAMPLE_PROJECT_RELATIONSHIP_FROZEN_CHECK,
    DISABLE TRIGGER ADD_SAMPLE_TO_SPACE_CHECK,
    DISABLE TRIGGER SAMPLE_SPACE_RELATIONSHIP_FROZEN_CHECK,
    DISABLE TRIGGER TRASH_SAMPLE_FROM_PROJECT_CHECK,
    DISABLE TRIGGER DELETE_SAMPLE_FROM_PROJECT_CHECK,
    DISABLE TRIGGER TRASH_SAMPLE_FROM_EXPERIMENT_CHECK,
    DISABLE TRIGGER DELETE_SAMPLE_FROM_EXPERIMENT_CHECK,
    DISABLE TRIGGER TRASH_SAMPLE_FROM_CONTAINER_CHECK,
    DISABLE TRIGGER DELETE_SAMPLE_FROM_CONTAINER_CHECK;

ALTER TABLE sample_properties
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_INSERT_PROPERTY,
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    DISABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_DELETE_PROPERTY;

-- Experiments

ALTER TABLE experiments_all
    DISABLE TRIGGER MELT_EXPERIMENT_FOR,
    DISABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_TRASH,
    DISABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_DELETE,
    DISABLE TRIGGER ADD_EXPERIMENT_TO_PROJECT_CHECK,
    DISABLE TRIGGER EXPERIMENT_PROJECT_RELATIONSHIP_FROZEN_CHECK,
    DISABLE TRIGGER TRASH_EXPERIMENT_FROM_PROJECT_CHECK,
    DISABLE TRIGGER DELETE_EXPERIMENT_FROM_PROJECT_CHECK;

ALTER TABLE experiment_properties
    DISABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_INSERT_PROPERTY,
    DISABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    DISABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_DELETE_PROPERTY;

-- Data sets

ALTER TABLE data_all
    DISABLE TRIGGER MELT_DATA_SET_FOR,
    DISABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_TRASH,
    DISABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_DELETE,
    DISABLE TRIGGER ADD_DATA_SET_TO_EXPERIMENT_CHECK,
    DISABLE TRIGGER DATA_SET_EXPERIMENT_RELATIONSHIP_FROZEN_CHECK_ON_UPDATE,
    DISABLE TRIGGER ADD_DATA_SET_TO_SAMPLE_CHECK,
    DISABLE TRIGGER DATA_SET_SAMPLE_RELATIONSHIP_FROZEN_CHECK_ON_UPDATE,
    DISABLE TRIGGER TRASH_DATA_SET_FROM_EXPERIMENT_CHECK,
    DISABLE TRIGGER DELETE_DATA_SET_FROM_EXPERIMENT_CHECK,
    DISABLE TRIGGER TRASH_DATA_SET_FROM_SAMPLE_CHECK,
    DISABLE TRIGGER DELETE_DATA_SET_FROM_SAMPLE_CHECK;

ALTER TABLE data_set_properties
    DISABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_INSERT_PROPERTY,
    DISABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    DISABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_DELETE_PROPERTY;
