-- Enabling triggers

-- Samples

ALTER TABLE samples_all
    ENABLE TRIGGER MELT_SAMPLE_FOR,
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_TRASH,
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_DELETE,
    ENABLE TRIGGER ADD_SAMPLE_TO_CONTAINER_CHECK,
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_SET_CONTAINER,
    ENABLE TRIGGER ADD_SAMPLE_TO_EXPERIMENT_CHECK,
    ENABLE TRIGGER SAMPLE_EXPERIMENT_RELATIONSHIP_FROZEN_CHECK,
    ENABLE TRIGGER ADD_SAMPLE_TO_PROJECT_CHECK,
    ENABLE TRIGGER SAMPLE_PROJECT_RELATIONSHIP_FROZEN_CHECK,
    ENABLE TRIGGER ADD_SAMPLE_TO_SPACE_CHECK,
    ENABLE TRIGGER SAMPLE_SPACE_RELATIONSHIP_FROZEN_CHECK,
    ENABLE TRIGGER TRASH_SAMPLE_FROM_PROJECT_CHECK,
    ENABLE TRIGGER DELETE_SAMPLE_FROM_PROJECT_CHECK,
    ENABLE TRIGGER TRASH_SAMPLE_FROM_EXPERIMENT_CHECK,
    ENABLE TRIGGER DELETE_SAMPLE_FROM_EXPERIMENT_CHECK,
    ENABLE TRIGGER TRASH_SAMPLE_FROM_CONTAINER_CHECK,
    ENABLE TRIGGER DELETE_SAMPLE_FROM_CONTAINER_CHECK;

ALTER TABLE sample_properties
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_INSERT_PROPERTY,
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    ENABLE TRIGGER SAMPLE_FROZEN_CHECK_ON_DELETE_PROPERTY;

-- Experiments

ALTER TABLE experiments_all
    ENABLE TRIGGER MELT_EXPERIMENT_FOR,
    ENABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_TRASH,
    ENABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_DELETE,
    ENABLE TRIGGER ADD_EXPERIMENT_TO_PROJECT_CHECK,
    ENABLE TRIGGER EXPERIMENT_PROJECT_RELATIONSHIP_FROZEN_CHECK,
    ENABLE TRIGGER TRASH_EXPERIMENT_FROM_PROJECT_CHECK,
    ENABLE TRIGGER DELETE_EXPERIMENT_FROM_PROJECT_CHECK;

ALTER TABLE experiment_properties
    ENABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_INSERT_PROPERTY,
    ENABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    ENABLE TRIGGER EXPERIMENT_FROZEN_CHECK_ON_DELETE_PROPERTY;

-- Data sets

ALTER TABLE data_all
    ENABLE TRIGGER MELT_DATA_SET_FOR,
    ENABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_TRASH,
    ENABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_DELETE,
    ENABLE TRIGGER ADD_DATA_SET_TO_EXPERIMENT_CHECK,
    ENABLE TRIGGER DATA_SET_EXPERIMENT_RELATIONSHIP_FROZEN_CHECK_ON_UPDATE,
    ENABLE TRIGGER ADD_DATA_SET_TO_SAMPLE_CHECK,
    ENABLE TRIGGER DATA_SET_SAMPLE_RELATIONSHIP_FROZEN_CHECK_ON_UPDATE,
    ENABLE TRIGGER TRASH_DATA_SET_FROM_EXPERIMENT_CHECK,
    ENABLE TRIGGER DELETE_DATA_SET_FROM_EXPERIMENT_CHECK,
    ENABLE TRIGGER TRASH_DATA_SET_FROM_SAMPLE_CHECK,
    ENABLE TRIGGER DELETE_DATA_SET_FROM_SAMPLE_CHECK;

ALTER TABLE data_set_properties
    ENABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_INSERT_PROPERTY,
    ENABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_CHANGE_PROPERTY,
    ENABLE TRIGGER DATA_SET_FROZEN_CHECK_ON_DELETE_PROPERTY;
