# -*- coding: utf-8 -*-
import ch.systemsx.cisd.openbis.generic.server.jython.api.v1.DataType as DataType

tr = service.transaction()


file_type_HDF5 = tr.createNewFileFormatType('HDF5')
file_type_HDF5.setDescription('Hierarchical Data Format File, version 5')

file_type_PROPRIETARY = tr.createNewFileFormatType('PROPRIETARY')
file_type_PROPRIETARY.setDescription('Proprietary Format File')

file_type_SRF = tr.createNewFileFormatType('SRF')
file_type_SRF.setDescription('Sequence Read Format File')

file_type_TIFF = tr.createNewFileFormatType('TIFF')
file_type_TIFF.setDescription('TIFF File')

file_type_TSV = tr.createNewFileFormatType('TSV')
file_type_TSV.setDescription('Tab Separated Values File')

file_type_XML = tr.createNewFileFormatType('XML')
file_type_XML.setDescription('XML File')

file_type_MULTI_STRAIN_EXCEL_V1 = tr.createNewFileFormatType('MULTI_STRAIN_EXCEL_V1')
file_type_MULTI_STRAIN_EXCEL_V1.setDescription('An Excel file with data for multiple strains')

vocabulary_STORAGE_FORMAT = tr.createNewVocabulary('STORAGE_FORMAT')
vocabulary_STORAGE_FORMAT.setDescription('The on-disk storage format of a data set')
vocabulary_STORAGE_FORMAT.setUrlTemplate(None)
vocabulary_STORAGE_FORMAT.setManagedInternally(True)
vocabulary_STORAGE_FORMAT.setInternalNamespace(True)
vocabulary_STORAGE_FORMAT.setChosenFromList(True)

vocabulary_term_STORAGE_FORMAT_BDS_DIRECTORY = tr.createNewVocabularyTerm('BDS_DIRECTORY')
vocabulary_term_STORAGE_FORMAT_BDS_DIRECTORY.setDescription(None)
vocabulary_term_STORAGE_FORMAT_BDS_DIRECTORY.setLabel(None)
vocabulary_term_STORAGE_FORMAT_BDS_DIRECTORY.setOrdinal(2)
vocabulary_STORAGE_FORMAT.addTerm(vocabulary_term_STORAGE_FORMAT_BDS_DIRECTORY)

vocabulary_term_STORAGE_FORMAT_PROPRIETARY = tr.createNewVocabularyTerm('PROPRIETARY')
vocabulary_term_STORAGE_FORMAT_PROPRIETARY.setDescription(None)
vocabulary_term_STORAGE_FORMAT_PROPRIETARY.setLabel(None)
vocabulary_term_STORAGE_FORMAT_PROPRIETARY.setOrdinal(1)
vocabulary_STORAGE_FORMAT.addTerm(vocabulary_term_STORAGE_FORMAT_PROPRIETARY)

vocabulary_CELL_LOCATION = tr.createNewVocabulary('CELL_LOCATION')
vocabulary_CELL_LOCATION.setDescription('Cell Location')
vocabulary_CELL_LOCATION.setUrlTemplate(None)
vocabulary_CELL_LOCATION.setManagedInternally(False)
vocabulary_CELL_LOCATION.setInternalNamespace(False)
vocabulary_CELL_LOCATION.setChosenFromList(True)

vocabulary_term_CELL_LOCATION_CE = tr.createNewVocabularyTerm('CE')
vocabulary_term_CELL_LOCATION_CE.setDescription(None)
vocabulary_term_CELL_LOCATION_CE.setLabel(None)
vocabulary_term_CELL_LOCATION_CE.setOrdinal(1)
vocabulary_CELL_LOCATION.addTerm(vocabulary_term_CELL_LOCATION_CE)

vocabulary_term_CELL_LOCATION_ME = tr.createNewVocabularyTerm('ME')
vocabulary_term_CELL_LOCATION_ME.setDescription(None)
vocabulary_term_CELL_LOCATION_ME.setLabel(None)
vocabulary_term_CELL_LOCATION_ME.setOrdinal(3)
vocabulary_CELL_LOCATION.addTerm(vocabulary_term_CELL_LOCATION_ME)

vocabulary_term_CELL_LOCATION_ES = tr.createNewVocabularyTerm('ES')
vocabulary_term_CELL_LOCATION_ES.setDescription(None)
vocabulary_term_CELL_LOCATION_ES.setLabel(None)
vocabulary_term_CELL_LOCATION_ES.setOrdinal(2)
vocabulary_CELL_LOCATION.addTerm(vocabulary_term_CELL_LOCATION_ES)

vocabulary_term_CELL_LOCATION_NC = tr.createNewVocabularyTerm('NC')
vocabulary_term_CELL_LOCATION_NC.setDescription(None)
vocabulary_term_CELL_LOCATION_NC.setLabel(None)
vocabulary_term_CELL_LOCATION_NC.setOrdinal(5)
vocabulary_CELL_LOCATION.addTerm(vocabulary_term_CELL_LOCATION_NC)

vocabulary_term_CELL_LOCATION_CY = tr.createNewVocabularyTerm('CY')
vocabulary_term_CELL_LOCATION_CY.setDescription(None)
vocabulary_term_CELL_LOCATION_CY.setLabel(None)
vocabulary_term_CELL_LOCATION_CY.setOrdinal(4)
vocabulary_CELL_LOCATION.addTerm(vocabulary_term_CELL_LOCATION_CY)

vocabulary_CONTAINER = tr.createNewVocabulary('CONTAINER')
vocabulary_CONTAINER.setDescription('Container in which the experiment was performed.')
vocabulary_CONTAINER.setUrlTemplate(None)
vocabulary_CONTAINER.setManagedInternally(False)
vocabulary_CONTAINER.setInternalNamespace(False)
vocabulary_CONTAINER.setChosenFromList(True)

vocabulary_term_CONTAINER_96DWP = tr.createNewVocabularyTerm('96-DWP')
vocabulary_term_CONTAINER_96DWP.setDescription(None)
vocabulary_term_CONTAINER_96DWP.setLabel('96-well deep well (2mL) plate')
vocabulary_term_CONTAINER_96DWP.setOrdinal(3)
vocabulary_CONTAINER.addTerm(vocabulary_term_CONTAINER_96DWP)

vocabulary_term_CONTAINER_FLASK = tr.createNewVocabularyTerm('FLASK')
vocabulary_term_CONTAINER_FLASK.setDescription(None)
vocabulary_term_CONTAINER_FLASK.setLabel('non-baffled shake flask')
vocabulary_term_CONTAINER_FLASK.setOrdinal(1)
vocabulary_CONTAINER.addTerm(vocabulary_term_CONTAINER_FLASK)

vocabulary_term_CONTAINER_96MICRO = tr.createNewVocabularyTerm('96-MICRO')
vocabulary_term_CONTAINER_96MICRO.setDescription(None)
vocabulary_term_CONTAINER_96MICRO.setLabel('96-well microtiter (400ul) plate')
vocabulary_term_CONTAINER_96MICRO.setOrdinal(2)
vocabulary_CONTAINER.addTerm(vocabulary_term_CONTAINER_96MICRO)

vocabulary_DEVICE = tr.createNewVocabulary('DEVICE')
vocabulary_DEVICE.setDescription('Devices used to produce measurements.')
vocabulary_DEVICE.setUrlTemplate(None)
vocabulary_DEVICE.setManagedInternally(False)
vocabulary_DEVICE.setInternalNamespace(False)
vocabulary_DEVICE.setChosenFromList(True)

vocabulary_term_DEVICE_ORBITRAP = tr.createNewVocabularyTerm('ORBITRAP')
vocabulary_term_DEVICE_ORBITRAP.setDescription(None)
vocabulary_term_DEVICE_ORBITRAP.setLabel(None)
vocabulary_term_DEVICE_ORBITRAP.setOrdinal(1)
vocabulary_DEVICE.addTerm(vocabulary_term_DEVICE_ORBITRAP)

vocabulary_GROWTH_MEDIA = tr.createNewVocabulary('GROWTH_MEDIA')
vocabulary_GROWTH_MEDIA.setDescription('Growth media for B. Subtilis.')
vocabulary_GROWTH_MEDIA.setUrlTemplate(None)
vocabulary_GROWTH_MEDIA.setManagedInternally(False)
vocabulary_GROWTH_MEDIA.setInternalNamespace(False)
vocabulary_GROWTH_MEDIA.setChosenFromList(True)

vocabulary_term_GROWTH_MEDIA_MALATE = tr.createNewVocabularyTerm('MALATE')
vocabulary_term_GROWTH_MEDIA_MALATE.setDescription(None)
vocabulary_term_GROWTH_MEDIA_MALATE.setLabel(None)
vocabulary_term_GROWTH_MEDIA_MALATE.setOrdinal(1)
vocabulary_GROWTH_MEDIA.addTerm(vocabulary_term_GROWTH_MEDIA_MALATE)

vocabulary_term_GROWTH_MEDIA_GLUCOSE = tr.createNewVocabularyTerm('GLUCOSE')
vocabulary_term_GROWTH_MEDIA_GLUCOSE.setDescription(None)
vocabulary_term_GROWTH_MEDIA_GLUCOSE.setLabel(None)
vocabulary_term_GROWTH_MEDIA_GLUCOSE.setOrdinal(2)
vocabulary_GROWTH_MEDIA.addTerm(vocabulary_term_GROWTH_MEDIA_GLUCOSE)

vocabulary_term_GROWTH_MEDIA_NMS = tr.createNewVocabularyTerm('NMS')
vocabulary_term_GROWTH_MEDIA_NMS.setDescription('glucose+citrate+amino acids. See SOPs or PPT in Kosei's email for complete recipe.')
vocabulary_term_GROWTH_MEDIA_NMS.setLabel('NMS (4g/L glucose)')
vocabulary_term_GROWTH_MEDIA_NMS.setOrdinal(3)
vocabulary_GROWTH_MEDIA.addTerm(vocabulary_term_GROWTH_MEDIA_NMS)

vocabulary_SCALE = tr.createNewVocabulary('SCALE')
vocabulary_SCALE.setDescription('Scale')
vocabulary_SCALE.setUrlTemplate(None)
vocabulary_SCALE.setManagedInternally(False)
vocabulary_SCALE.setInternalNamespace(False)
vocabulary_SCALE.setChosenFromList(True)

vocabulary_term_SCALE_LOG2 = tr.createNewVocabularyTerm('LOG2')
vocabulary_term_SCALE_LOG2.setDescription(None)
vocabulary_term_SCALE_LOG2.setLabel(None)
vocabulary_term_SCALE_LOG2.setOrdinal(2)
vocabulary_SCALE.addTerm(vocabulary_term_SCALE_LOG2)

vocabulary_term_SCALE_LIN = tr.createNewVocabularyTerm('LIN')
vocabulary_term_SCALE_LIN.setDescription(None)
vocabulary_term_SCALE_LIN.setLabel(None)
vocabulary_term_SCALE_LIN.setOrdinal(1)
vocabulary_SCALE.addTerm(vocabulary_term_SCALE_LIN)

vocabulary_term_SCALE_LOG10 = tr.createNewVocabularyTerm('LOG10')
vocabulary_term_SCALE_LOG10.setDescription(None)
vocabulary_term_SCALE_LOG10.setLabel(None)
vocabulary_term_SCALE_LOG10.setOrdinal(3)
vocabulary_SCALE.addTerm(vocabulary_term_SCALE_LOG10)

vocabulary_term_SCALE_LN = tr.createNewVocabularyTerm('LN')
vocabulary_term_SCALE_LN.setDescription(None)
vocabulary_term_SCALE_LN.setLabel(None)
vocabulary_term_SCALE_LN.setOrdinal(4)
vocabulary_SCALE.addTerm(vocabulary_term_SCALE_LN)

vocabulary_TECHNOLOGY = tr.createNewVocabulary('TECHNOLOGY')
vocabulary_TECHNOLOGY.setDescription('Technologies used in BaSynthec')
vocabulary_TECHNOLOGY.setUrlTemplate(None)
vocabulary_TECHNOLOGY.setManagedInternally(False)
vocabulary_TECHNOLOGY.setInternalNamespace(False)
vocabulary_TECHNOLOGY.setChosenFromList(True)

vocabulary_term_TECHNOLOGY_METABOLOMICS = tr.createNewVocabularyTerm('METABOLOMICS')
vocabulary_term_TECHNOLOGY_METABOLOMICS.setDescription(None)
vocabulary_term_TECHNOLOGY_METABOLOMICS.setLabel(None)
vocabulary_term_TECHNOLOGY_METABOLOMICS.setOrdinal(1)
vocabulary_TECHNOLOGY.addTerm(vocabulary_term_TECHNOLOGY_METABOLOMICS)

vocabulary_term_TECHNOLOGY_PROTEOMICS = tr.createNewVocabularyTerm('PROTEOMICS')
vocabulary_term_TECHNOLOGY_PROTEOMICS.setDescription(None)
vocabulary_term_TECHNOLOGY_PROTEOMICS.setLabel(None)
vocabulary_term_TECHNOLOGY_PROTEOMICS.setOrdinal(3)
vocabulary_TECHNOLOGY.addTerm(vocabulary_term_TECHNOLOGY_PROTEOMICS)

vocabulary_term_TECHNOLOGY_PHYSIOLOGY = tr.createNewVocabularyTerm('PHYSIOLOGY')
vocabulary_term_TECHNOLOGY_PHYSIOLOGY.setDescription(None)
vocabulary_term_TECHNOLOGY_PHYSIOLOGY.setLabel(None)
vocabulary_term_TECHNOLOGY_PHYSIOLOGY.setOrdinal(2)
vocabulary_TECHNOLOGY.addTerm(vocabulary_term_TECHNOLOGY_PHYSIOLOGY)

vocabulary_term_TECHNOLOGY_TRANSCRIPTOMICS = tr.createNewVocabularyTerm('TRANSCRIPTOMICS')
vocabulary_term_TECHNOLOGY_TRANSCRIPTOMICS.setDescription(None)
vocabulary_term_TECHNOLOGY_TRANSCRIPTOMICS.setLabel(None)
vocabulary_term_TECHNOLOGY_TRANSCRIPTOMICS.setOrdinal(4)
vocabulary_TECHNOLOGY.addTerm(vocabulary_term_TECHNOLOGY_TRANSCRIPTOMICS)

vocabulary_TEMPERATURE = tr.createNewVocabulary('TEMPERATURE')
vocabulary_TEMPERATURE.setDescription('Temperature the experiment was conducted under')
vocabulary_TEMPERATURE.setUrlTemplate(None)
vocabulary_TEMPERATURE.setManagedInternally(False)
vocabulary_TEMPERATURE.setInternalNamespace(False)
vocabulary_TEMPERATURE.setChosenFromList(True)

vocabulary_term_TEMPERATURE_40 = tr.createNewVocabularyTerm('40')
vocabulary_term_TEMPERATURE_40.setDescription(None)
vocabulary_term_TEMPERATURE_40.setLabel(None)
vocabulary_term_TEMPERATURE_40.setOrdinal(3)
vocabulary_TEMPERATURE.addTerm(vocabulary_term_TEMPERATURE_40)

vocabulary_term_TEMPERATURE_30 = tr.createNewVocabularyTerm('30')
vocabulary_term_TEMPERATURE_30.setDescription(None)
vocabulary_term_TEMPERATURE_30.setLabel(None)
vocabulary_term_TEMPERATURE_30.setOrdinal(2)
vocabulary_TEMPERATURE.addTerm(vocabulary_term_TEMPERATURE_30)

vocabulary_term_TEMPERATURE_20 = tr.createNewVocabularyTerm('20')
vocabulary_term_TEMPERATURE_20.setDescription(None)
vocabulary_term_TEMPERATURE_20.setLabel(None)
vocabulary_term_TEMPERATURE_20.setOrdinal(1)
vocabulary_TEMPERATURE.addTerm(vocabulary_term_TEMPERATURE_20)

vocabulary_TIMEPOINT_TYPE = tr.createNewVocabulary('TIMEPOINT_TYPE')
vocabulary_TIMEPOINT_TYPE.setDescription('Timepoint Type')
vocabulary_TIMEPOINT_TYPE.setUrlTemplate(None)
vocabulary_TIMEPOINT_TYPE.setManagedInternally(False)
vocabulary_TIMEPOINT_TYPE.setInternalNamespace(False)
vocabulary_TIMEPOINT_TYPE.setChosenFromList(True)

vocabulary_term_TIMEPOINT_TYPE_IN = tr.createNewVocabularyTerm('IN')
vocabulary_term_TIMEPOINT_TYPE_IN.setDescription(None)
vocabulary_term_TIMEPOINT_TYPE_IN.setLabel(None)
vocabulary_term_TIMEPOINT_TYPE_IN.setOrdinal(2)
vocabulary_TIMEPOINT_TYPE.addTerm(vocabulary_term_TIMEPOINT_TYPE_IN)

vocabulary_term_TIMEPOINT_TYPE_EX = tr.createNewVocabularyTerm('EX')
vocabulary_term_TIMEPOINT_TYPE_EX.setDescription(None)
vocabulary_term_TIMEPOINT_TYPE_EX.setLabel(None)
vocabulary_term_TIMEPOINT_TYPE_EX.setOrdinal(1)
vocabulary_TIMEPOINT_TYPE.addTerm(vocabulary_term_TIMEPOINT_TYPE_EX)

vocabulary_term_TIMEPOINT_TYPE_SI = tr.createNewVocabularyTerm('SI')
vocabulary_term_TIMEPOINT_TYPE_SI.setDescription(None)
vocabulary_term_TIMEPOINT_TYPE_SI.setLabel(None)
vocabulary_term_TIMEPOINT_TYPE_SI.setOrdinal(3)
vocabulary_TIMEPOINT_TYPE.addTerm(vocabulary_term_TIMEPOINT_TYPE_SI)

vocabulary_VALUE_TYPE = tr.createNewVocabulary('VALUE_TYPE')
vocabulary_VALUE_TYPE.setDescription('Value Type')
vocabulary_VALUE_TYPE.setUrlTemplate(None)
vocabulary_VALUE_TYPE.setManagedInternally(False)
vocabulary_VALUE_TYPE.setInternalNamespace(False)
vocabulary_VALUE_TYPE.setChosenFromList(True)

vocabulary_term_VALUE_TYPE_IQR = tr.createNewVocabularyTerm('IQR')
vocabulary_term_VALUE_TYPE_IQR.setDescription(None)
vocabulary_term_VALUE_TYPE_IQR.setLabel(None)
vocabulary_term_VALUE_TYPE_IQR.setOrdinal(7)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_IQR)

vocabulary_term_VALUE_TYPE_VAR = tr.createNewVocabularyTerm('VAR')
vocabulary_term_VALUE_TYPE_VAR.setDescription(None)
vocabulary_term_VALUE_TYPE_VAR.setLabel(None)
vocabulary_term_VALUE_TYPE_VAR.setOrdinal(5)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_VAR)

vocabulary_term_VALUE_TYPE_ERROR = tr.createNewVocabularyTerm('ERROR')
vocabulary_term_VALUE_TYPE_ERROR.setDescription(None)
vocabulary_term_VALUE_TYPE_ERROR.setLabel(None)
vocabulary_term_VALUE_TYPE_ERROR.setOrdinal(6)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_ERROR)

vocabulary_term_VALUE_TYPE_VALUE = tr.createNewVocabularyTerm('VALUE')
vocabulary_term_VALUE_TYPE_VALUE.setDescription(None)
vocabulary_term_VALUE_TYPE_VALUE.setLabel(None)
vocabulary_term_VALUE_TYPE_VALUE.setOrdinal(1)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_VALUE)

vocabulary_term_VALUE_TYPE_MEAN = tr.createNewVocabularyTerm('MEAN')
vocabulary_term_VALUE_TYPE_MEAN.setDescription(None)
vocabulary_term_VALUE_TYPE_MEAN.setLabel(None)
vocabulary_term_VALUE_TYPE_MEAN.setOrdinal(2)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_MEAN)

vocabulary_term_VALUE_TYPE_STD = tr.createNewVocabularyTerm('STD')
vocabulary_term_VALUE_TYPE_STD.setDescription(None)
vocabulary_term_VALUE_TYPE_STD.setLabel(None)
vocabulary_term_VALUE_TYPE_STD.setOrdinal(4)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_STD)

vocabulary_term_VALUE_TYPE_MEDIAN = tr.createNewVocabularyTerm('MEDIAN')
vocabulary_term_VALUE_TYPE_MEDIAN.setDescription(None)
vocabulary_term_VALUE_TYPE_MEDIAN.setLabel(None)
vocabulary_term_VALUE_TYPE_MEDIAN.setOrdinal(3)
vocabulary_VALUE_TYPE.addTerm(vocabulary_term_VALUE_TYPE_MEDIAN)

vocabulary_VALUE_UNIT = tr.createNewVocabulary('VALUE_UNIT')
vocabulary_VALUE_UNIT.setDescription('Value Unit')
vocabulary_VALUE_UNIT.setUrlTemplate(None)
vocabulary_VALUE_UNIT.setManagedInternally(False)
vocabulary_VALUE_UNIT.setInternalNamespace(False)
vocabulary_VALUE_UNIT.setChosenFromList(True)

vocabulary_term_VALUE_UNIT_PERCENT = tr.createNewVocabularyTerm('PERCENT')
vocabulary_term_VALUE_UNIT_PERCENT.setDescription(None)
vocabulary_term_VALUE_UNIT_PERCENT.setLabel(None)
vocabulary_term_VALUE_UNIT_PERCENT.setOrdinal(3)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_PERCENT)

vocabulary_term_VALUE_UNIT_MM = tr.createNewVocabularyTerm('MM')
vocabulary_term_VALUE_UNIT_MM.setDescription(None)
vocabulary_term_VALUE_UNIT_MM.setLabel(None)
vocabulary_term_VALUE_UNIT_MM.setOrdinal(1)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_MM)

vocabulary_term_VALUE_UNIT_RATIOCS = tr.createNewVocabularyTerm('RATIOCS')
vocabulary_term_VALUE_UNIT_RATIOCS.setDescription(None)
vocabulary_term_VALUE_UNIT_RATIOCS.setLabel(None)
vocabulary_term_VALUE_UNIT_RATIOCS.setOrdinal(5)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_RATIOCS)

vocabulary_term_VALUE_UNIT_RATIOT1 = tr.createNewVocabularyTerm('RATIOT1')
vocabulary_term_VALUE_UNIT_RATIOT1.setDescription(None)
vocabulary_term_VALUE_UNIT_RATIOT1.setLabel(None)
vocabulary_term_VALUE_UNIT_RATIOT1.setOrdinal(4)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_RATIOT1)

vocabulary_term_VALUE_UNIT_AU = tr.createNewVocabularyTerm('AU')
vocabulary_term_VALUE_UNIT_AU.setDescription(None)
vocabulary_term_VALUE_UNIT_AU.setLabel(None)
vocabulary_term_VALUE_UNIT_AU.setOrdinal(6)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_AU)

vocabulary_term_VALUE_UNIT_UM = tr.createNewVocabularyTerm('UM')
vocabulary_term_VALUE_UNIT_UM.setDescription(None)
vocabulary_term_VALUE_UNIT_UM.setLabel(None)
vocabulary_term_VALUE_UNIT_UM.setOrdinal(2)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_UM)

vocabulary_term_VALUE_UNIT_DIMENSIONLESS = tr.createNewVocabularyTerm('DIMENSIONLESS')
vocabulary_term_VALUE_UNIT_DIMENSIONLESS.setDescription(None)
vocabulary_term_VALUE_UNIT_DIMENSIONLESS.setLabel(None)
vocabulary_term_VALUE_UNIT_DIMENSIONLESS.setOrdinal(7)
vocabulary_VALUE_UNIT.addTerm(vocabulary_term_VALUE_UNIT_DIMENSIONLESS)

exp_type_BASYNTHEC = tr.createNewExperimentType('BASYNTHEC')
exp_type_BASYNTHEC.setDescription('The BaSynthec experiment type.')

data_set_type_EXCEL_ORIGINAL = tr.createNewDataSetType('EXCEL_ORIGINAL')
data_set_type_EXCEL_ORIGINAL.setDescription('Excel data')
data_set_type_EXCEL_ORIGINAL.setContainerType(False)

data_set_type_METABOLITE_INTENSITIES = tr.createNewDataSetType('METABOLITE_INTENSITIES')
data_set_type_METABOLITE_INTENSITIES.setDescription('Metabolite intensities')
data_set_type_METABOLITE_INTENSITIES.setContainerType(True)

data_set_type_OD600 = tr.createNewDataSetType('OD600')
data_set_type_OD600.setDescription('Growth profiles')
data_set_type_OD600.setContainerType(True)

data_set_type_PROTEIN_QUANTIFICATIONS = tr.createNewDataSetType('PROTEIN_QUANTIFICATIONS')
data_set_type_PROTEIN_QUANTIFICATIONS.setDescription('Protein quantifications')
data_set_type_PROTEIN_QUANTIFICATIONS.setContainerType(True)

data_set_type_RAW = tr.createNewDataSetType('RAW')
data_set_type_RAW.setDescription('Raw data')
data_set_type_RAW.setContainerType(False)

data_set_type_TRANSCRIPTOMICS = tr.createNewDataSetType('TRANSCRIPTOMICS')
data_set_type_TRANSCRIPTOMICS.setDescription('Transcriptomics data')
data_set_type_TRANSCRIPTOMICS.setContainerType(True)

data_set_type_TSV_EXPORT = tr.createNewDataSetType('TSV_EXPORT')
data_set_type_TSV_EXPORT.setDescription('An export of the data containing one strain per file.')
data_set_type_TSV_EXPORT.setContainerType(False)

data_set_type_TSV_MULTISTRAIN_EXPORT = tr.createNewDataSetType('TSV_MULTISTRAIN_EXPORT')
data_set_type_TSV_MULTISTRAIN_EXPORT.setDescription('An export of the data containing multiple strains per file.')
data_set_type_TSV_MULTISTRAIN_EXPORT.setContainerType(False)

data_set_type_UNKNOWN = tr.createNewDataSetType('UNKNOWN')
data_set_type_UNKNOWN.setDescription('Unknown')
data_set_type_UNKNOWN.setContainerType(False)

material_type_STRAIN = tr.createNewMaterialType('STRAIN')
material_type_STRAIN.setDescription('Strain')

prop_type_CELL_LOCATION = tr.createNewPropertyType('CELL_LOCATION', DataType.CONTROLLEDVOCABULARY)
prop_type_CELL_LOCATION.setLabel('Cell Location')
prop_type_CELL_LOCATION.setManagedInternally(False)
prop_type_CELL_LOCATION.setInternalNamespace(False)

prop_type_CELL_LOCATION.setVocabulary(vocabulary_CELL_LOCATION)

prop_type_COMMENTS = tr.createNewPropertyType('COMMENTS', DataType.MULTILINE_VARCHAR)
prop_type_COMMENTS.setLabel('Comments')
prop_type_COMMENTS.setManagedInternally(False)
prop_type_COMMENTS.setInternalNamespace(False)


prop_type_CONTAINER = tr.createNewPropertyType('CONTAINER', DataType.CONTROLLEDVOCABULARY)
prop_type_CONTAINER.setLabel('Container')
prop_type_CONTAINER.setManagedInternally(False)
prop_type_CONTAINER.setInternalNamespace(False)

prop_type_CONTAINER.setVocabulary(vocabulary_CONTAINER)

prop_type_CONTAINER_VOLUME = tr.createNewPropertyType('CONTAINER_VOLUME', DataType.VARCHAR)
prop_type_CONTAINER_VOLUME.setLabel('Container Volume')
prop_type_CONTAINER_VOLUME.setManagedInternally(False)
prop_type_CONTAINER_VOLUME.setInternalNamespace(False)


prop_type_DATA_TYPE = tr.createNewPropertyType('DATA_TYPE', DataType.VARCHAR)
prop_type_DATA_TYPE.setLabel('Data Type')
prop_type_DATA_TYPE.setManagedInternally(False)
prop_type_DATA_TYPE.setInternalNamespace(False)


prop_type_DESCRIPTION = tr.createNewPropertyType('DESCRIPTION', DataType.VARCHAR)
prop_type_DESCRIPTION.setLabel('Description')
prop_type_DESCRIPTION.setManagedInternally(False)
prop_type_DESCRIPTION.setInternalNamespace(False)


prop_type_DEVICE = tr.createNewPropertyType('DEVICE', DataType.CONTROLLEDVOCABULARY)
prop_type_DEVICE.setLabel('Device')
prop_type_DEVICE.setManagedInternally(False)
prop_type_DEVICE.setInternalNamespace(False)

prop_type_DEVICE.setVocabulary(vocabulary_DEVICE)

prop_type_EXPERIMENT_DATE = tr.createNewPropertyType('EXPERIMENT_DATE', DataType.TIMESTAMP)
prop_type_EXPERIMENT_DATE.setLabel('Experiment Date')
prop_type_EXPERIMENT_DATE.setManagedInternally(False)
prop_type_EXPERIMENT_DATE.setInternalNamespace(False)


prop_type_MEDIUM = tr.createNewPropertyType('MEDIUM', DataType.CONTROLLEDVOCABULARY)
prop_type_MEDIUM.setLabel('Medium')
prop_type_MEDIUM.setManagedInternally(False)
prop_type_MEDIUM.setInternalNamespace(False)

prop_type_MEDIUM.setVocabulary(vocabulary_GROWTH_MEDIA)

prop_type_MISC_GROWTH_CONDITIONS = tr.createNewPropertyType('MISC_GROWTH_CONDITIONS', DataType.MULTILINE_VARCHAR)
prop_type_MISC_GROWTH_CONDITIONS.setLabel('Growth Conditions')
prop_type_MISC_GROWTH_CONDITIONS.setManagedInternally(False)
prop_type_MISC_GROWTH_CONDITIONS.setInternalNamespace(False)


prop_type_OPERATOR = tr.createNewPropertyType('OPERATOR', DataType.VARCHAR)
prop_type_OPERATOR.setLabel('Operator')
prop_type_OPERATOR.setManagedInternally(False)
prop_type_OPERATOR.setInternalNamespace(False)


prop_type_REFERENCE_STRAIN = tr.createNewPropertyType('REFERENCE_STRAIN', DataType.MATERIAL)
prop_type_REFERENCE_STRAIN.setLabel('Reference Strain')
prop_type_REFERENCE_STRAIN.setManagedInternally(False)
prop_type_REFERENCE_STRAIN.setInternalNamespace(False)
prop_type_REFERENCE_STRAIN.setMaterialType(material_type_STRAIN)

prop_type_SCALE = tr.createNewPropertyType('SCALE', DataType.CONTROLLEDVOCABULARY)
prop_type_SCALE.setLabel('Scale')
prop_type_SCALE.setManagedInternally(False)
prop_type_SCALE.setInternalNamespace(False)

prop_type_SCALE.setVocabulary(vocabulary_SCALE)

prop_type_SHAKER_RPM = tr.createNewPropertyType('SHAKER_RPM', DataType.INTEGER)
prop_type_SHAKER_RPM.setLabel('Shaker RPM')
prop_type_SHAKER_RPM.setManagedInternally(False)
prop_type_SHAKER_RPM.setInternalNamespace(False)


prop_type_STRAIN = tr.createNewPropertyType('STRAIN', DataType.MATERIAL)
prop_type_STRAIN.setLabel('Strain')
prop_type_STRAIN.setManagedInternally(False)
prop_type_STRAIN.setInternalNamespace(False)
prop_type_STRAIN.setMaterialType(material_type_STRAIN)

prop_type_STRAIN_NAME = tr.createNewPropertyType('STRAIN_NAME', DataType.VARCHAR)
prop_type_STRAIN_NAME.setLabel('Name')
prop_type_STRAIN_NAME.setManagedInternally(False)
prop_type_STRAIN_NAME.setInternalNamespace(False)


prop_type_STRAIN_NAMES = tr.createNewPropertyType('STRAIN_NAMES', DataType.VARCHAR)
prop_type_STRAIN_NAMES.setLabel('Strain Names')
prop_type_STRAIN_NAMES.setManagedInternally(False)
prop_type_STRAIN_NAMES.setInternalNamespace(False)


prop_type_TECHNOLOGY = tr.createNewPropertyType('TECHNOLOGY', DataType.CONTROLLEDVOCABULARY)
prop_type_TECHNOLOGY.setLabel('Technology')
prop_type_TECHNOLOGY.setManagedInternally(False)
prop_type_TECHNOLOGY.setInternalNamespace(False)

prop_type_TECHNOLOGY.setVocabulary(vocabulary_TECHNOLOGY)

prop_type_TEMPERATURE = tr.createNewPropertyType('TEMPERATURE', DataType.REAL)
prop_type_TEMPERATURE.setLabel('Temperature')
prop_type_TEMPERATURE.setManagedInternally(False)
prop_type_TEMPERATURE.setInternalNamespace(False)


prop_type_TIMEPOINT_TYPE = tr.createNewPropertyType('TIMEPOINT_TYPE', DataType.CONTROLLEDVOCABULARY)
prop_type_TIMEPOINT_TYPE.setLabel('Timepoint Type')
prop_type_TIMEPOINT_TYPE.setManagedInternally(False)
prop_type_TIMEPOINT_TYPE.setInternalNamespace(False)

prop_type_TIMEPOINT_TYPE.setVocabulary(vocabulary_TIMEPOINT_TYPE)

prop_type_VALUE_TYPE = tr.createNewPropertyType('VALUE_TYPE', DataType.CONTROLLEDVOCABULARY)
prop_type_VALUE_TYPE.setLabel('Value Type')
prop_type_VALUE_TYPE.setManagedInternally(False)
prop_type_VALUE_TYPE.setInternalNamespace(False)

prop_type_VALUE_TYPE.setVocabulary(vocabulary_VALUE_TYPE)

prop_type_VALUE_UNIT = tr.createNewPropertyType('VALUE_UNIT', DataType.CONTROLLEDVOCABULARY)
prop_type_VALUE_UNIT.setLabel('Value Unit')
prop_type_VALUE_UNIT.setManagedInternally(False)
prop_type_VALUE_UNIT.setInternalNamespace(False)

prop_type_VALUE_UNIT.setVocabulary(vocabulary_VALUE_UNIT)

assignment_EXPERIMENT_BASYNTHEC_DESCRIPTION = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_DESCRIPTION)
assignment_EXPERIMENT_BASYNTHEC_DESCRIPTION.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_DESCRIPTION.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_DESCRIPTION.setPositionInForms(1)

assignment_EXPERIMENT_BASYNTHEC_MEDIUM = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_MEDIUM)
assignment_EXPERIMENT_BASYNTHEC_MEDIUM.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_MEDIUM.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_MEDIUM.setPositionInForms(2)

assignment_EXPERIMENT_BASYNTHEC_TEMPERATURE = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_TEMPERATURE)
assignment_EXPERIMENT_BASYNTHEC_TEMPERATURE.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_TEMPERATURE.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_TEMPERATURE.setPositionInForms(3)

assignment_EXPERIMENT_BASYNTHEC_CONTAINER = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_CONTAINER)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER.setPositionInForms(5)

assignment_EXPERIMENT_BASYNTHEC_CONTAINER_VOLUME = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_CONTAINER_VOLUME)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER_VOLUME.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER_VOLUME.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_CONTAINER_VOLUME.setPositionInForms(6)

assignment_EXPERIMENT_BASYNTHEC_MISC_GROWTH_CONDITIONS = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_MISC_GROWTH_CONDITIONS)
assignment_EXPERIMENT_BASYNTHEC_MISC_GROWTH_CONDITIONS.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_MISC_GROWTH_CONDITIONS.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_MISC_GROWTH_CONDITIONS.setPositionInForms(7)

assignment_EXPERIMENT_BASYNTHEC_SHAKER_RPM = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_SHAKER_RPM)
assignment_EXPERIMENT_BASYNTHEC_SHAKER_RPM.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_SHAKER_RPM.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_SHAKER_RPM.setPositionInForms(8)

assignment_EXPERIMENT_BASYNTHEC_COMMENTS = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_COMMENTS)
assignment_EXPERIMENT_BASYNTHEC_COMMENTS.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_COMMENTS.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_COMMENTS.setPositionInForms(9)

assignment_EXPERIMENT_BASYNTHEC_EXPERIMENT_DATE = tr.assignPropertyType(exp_type_BASYNTHEC, prop_type_EXPERIMENT_DATE)
assignment_EXPERIMENT_BASYNTHEC_EXPERIMENT_DATE.setMandatory(False)
assignment_EXPERIMENT_BASYNTHEC_EXPERIMENT_DATE.setSection(None)
assignment_EXPERIMENT_BASYNTHEC_EXPERIMENT_DATE.setPositionInForms(10)

assignment_DATA_SET_EXCEL_ORIGINAL_DATA_TYPE = tr.assignPropertyType(data_set_type_EXCEL_ORIGINAL, prop_type_DATA_TYPE)
assignment_DATA_SET_EXCEL_ORIGINAL_DATA_TYPE.setMandatory(False)
assignment_DATA_SET_EXCEL_ORIGINAL_DATA_TYPE.setSection(None)
assignment_DATA_SET_EXCEL_ORIGINAL_DATA_TYPE.setPositionInForms(1)

assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_STRAIN)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN.setPositionInForms(1)

assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN_NAMES = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_STRAIN_NAMES)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN_NAMES.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN_NAMES.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_STRAIN_NAMES.setPositionInForms(2)

assignment_DATA_SET_METABOLITE_INTENSITIES_TIMEPOINT_TYPE = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_TIMEPOINT_TYPE)
assignment_DATA_SET_METABOLITE_INTENSITIES_TIMEPOINT_TYPE.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_TIMEPOINT_TYPE.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_TIMEPOINT_TYPE.setPositionInForms(3)

assignment_DATA_SET_METABOLITE_INTENSITIES_CELL_LOCATION = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_CELL_LOCATION)
assignment_DATA_SET_METABOLITE_INTENSITIES_CELL_LOCATION.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_CELL_LOCATION.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_CELL_LOCATION.setPositionInForms(4)

assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_TYPE = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_VALUE_TYPE)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_TYPE.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_TYPE.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_TYPE.setPositionInForms(5)

assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_UNIT = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_VALUE_UNIT)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_UNIT.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_UNIT.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_VALUE_UNIT.setPositionInForms(6)

assignment_DATA_SET_METABOLITE_INTENSITIES_SCALE = tr.assignPropertyType(data_set_type_METABOLITE_INTENSITIES, prop_type_SCALE)
assignment_DATA_SET_METABOLITE_INTENSITIES_SCALE.setMandatory(False)
assignment_DATA_SET_METABOLITE_INTENSITIES_SCALE.setSection(None)
assignment_DATA_SET_METABOLITE_INTENSITIES_SCALE.setPositionInForms(7)

assignment_DATA_SET_OD600_STRAIN = tr.assignPropertyType(data_set_type_OD600, prop_type_STRAIN)
assignment_DATA_SET_OD600_STRAIN.setMandatory(False)
assignment_DATA_SET_OD600_STRAIN.setSection(None)
assignment_DATA_SET_OD600_STRAIN.setPositionInForms(1)

assignment_DATA_SET_OD600_STRAIN_NAMES = tr.assignPropertyType(data_set_type_OD600, prop_type_STRAIN_NAMES)
assignment_DATA_SET_OD600_STRAIN_NAMES.setMandatory(False)
assignment_DATA_SET_OD600_STRAIN_NAMES.setSection(None)
assignment_DATA_SET_OD600_STRAIN_NAMES.setPositionInForms(2)

assignment_DATA_SET_OD600_TIMEPOINT_TYPE = tr.assignPropertyType(data_set_type_OD600, prop_type_TIMEPOINT_TYPE)
assignment_DATA_SET_OD600_TIMEPOINT_TYPE.setMandatory(False)
assignment_DATA_SET_OD600_TIMEPOINT_TYPE.setSection(None)
assignment_DATA_SET_OD600_TIMEPOINT_TYPE.setPositionInForms(3)

assignment_DATA_SET_OD600_CELL_LOCATION = tr.assignPropertyType(data_set_type_OD600, prop_type_CELL_LOCATION)
assignment_DATA_SET_OD600_CELL_LOCATION.setMandatory(False)
assignment_DATA_SET_OD600_CELL_LOCATION.setSection(None)
assignment_DATA_SET_OD600_CELL_LOCATION.setPositionInForms(4)

assignment_DATA_SET_OD600_VALUE_TYPE = tr.assignPropertyType(data_set_type_OD600, prop_type_VALUE_TYPE)
assignment_DATA_SET_OD600_VALUE_TYPE.setMandatory(False)
assignment_DATA_SET_OD600_VALUE_TYPE.setSection(None)
assignment_DATA_SET_OD600_VALUE_TYPE.setPositionInForms(5)

assignment_DATA_SET_OD600_VALUE_UNIT = tr.assignPropertyType(data_set_type_OD600, prop_type_VALUE_UNIT)
assignment_DATA_SET_OD600_VALUE_UNIT.setMandatory(False)
assignment_DATA_SET_OD600_VALUE_UNIT.setSection(None)
assignment_DATA_SET_OD600_VALUE_UNIT.setPositionInForms(6)

assignment_DATA_SET_OD600_SCALE = tr.assignPropertyType(data_set_type_OD600, prop_type_SCALE)
assignment_DATA_SET_OD600_SCALE.setMandatory(False)
assignment_DATA_SET_OD600_SCALE.setSection(None)
assignment_DATA_SET_OD600_SCALE.setPositionInForms(7)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_STRAIN)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN.setPositionInForms(1)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN_NAMES = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_STRAIN_NAMES)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN_NAMES.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN_NAMES.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_STRAIN_NAMES.setPositionInForms(2)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_TIMEPOINT_TYPE = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_TIMEPOINT_TYPE)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_TIMEPOINT_TYPE.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_TIMEPOINT_TYPE.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_TIMEPOINT_TYPE.setPositionInForms(3)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_CELL_LOCATION = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_CELL_LOCATION)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_CELL_LOCATION.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_CELL_LOCATION.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_CELL_LOCATION.setPositionInForms(4)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_VALUE_UNIT = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_VALUE_UNIT)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_VALUE_UNIT.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_VALUE_UNIT.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_VALUE_UNIT.setPositionInForms(6)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_SCALE = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_SCALE)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_SCALE.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_SCALE.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_SCALE.setPositionInForms(7)

assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_REFERENCE_STRAIN = tr.assignPropertyType(data_set_type_PROTEIN_QUANTIFICATIONS, prop_type_REFERENCE_STRAIN)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_REFERENCE_STRAIN.setMandatory(False)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_REFERENCE_STRAIN.setSection(None)
assignment_DATA_SET_PROTEIN_QUANTIFICATIONS_REFERENCE_STRAIN.setPositionInForms(8)

assignment_DATA_SET_RAW_STRAIN = tr.assignPropertyType(data_set_type_RAW, prop_type_STRAIN)
assignment_DATA_SET_RAW_STRAIN.setMandatory(True)
assignment_DATA_SET_RAW_STRAIN.setSection(None)
assignment_DATA_SET_RAW_STRAIN.setPositionInForms(1)

assignment_DATA_SET_RAW_TECHNOLOGY = tr.assignPropertyType(data_set_type_RAW, prop_type_TECHNOLOGY)
assignment_DATA_SET_RAW_TECHNOLOGY.setMandatory(True)
assignment_DATA_SET_RAW_TECHNOLOGY.setSection(None)
assignment_DATA_SET_RAW_TECHNOLOGY.setPositionInForms(2)

assignment_DATA_SET_RAW_DEVICE = tr.assignPropertyType(data_set_type_RAW, prop_type_DEVICE)
assignment_DATA_SET_RAW_DEVICE.setMandatory(False)
assignment_DATA_SET_RAW_DEVICE.setSection(None)
assignment_DATA_SET_RAW_DEVICE.setPositionInForms(3)

assignment_DATA_SET_RAW_OPERATOR = tr.assignPropertyType(data_set_type_RAW, prop_type_OPERATOR)
assignment_DATA_SET_RAW_OPERATOR.setMandatory(False)
assignment_DATA_SET_RAW_OPERATOR.setSection(None)
assignment_DATA_SET_RAW_OPERATOR.setPositionInForms(4)

assignment_MATERIAL_STRAIN_STRAIN_NAME = tr.assignPropertyType(material_type_STRAIN, prop_type_STRAIN_NAME)
assignment_MATERIAL_STRAIN_STRAIN_NAME.setMandatory(True)
assignment_MATERIAL_STRAIN_STRAIN_NAME.setSection(None)
assignment_MATERIAL_STRAIN_STRAIN_NAME.setPositionInForms(1)

assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_STRAIN)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN.setPositionInForms(1)

assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN_NAMES = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_STRAIN_NAMES)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN_NAMES.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN_NAMES.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_STRAIN_NAMES.setPositionInForms(2)

assignment_DATA_SET_TRANSCRIPTOMICS_TIMEPOINT_TYPE = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_TIMEPOINT_TYPE)
assignment_DATA_SET_TRANSCRIPTOMICS_TIMEPOINT_TYPE.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_TIMEPOINT_TYPE.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_TIMEPOINT_TYPE.setPositionInForms(3)

assignment_DATA_SET_TRANSCRIPTOMICS_CELL_LOCATION = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_CELL_LOCATION)
assignment_DATA_SET_TRANSCRIPTOMICS_CELL_LOCATION.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_CELL_LOCATION.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_CELL_LOCATION.setPositionInForms(4)

assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_TYPE = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_VALUE_TYPE)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_TYPE.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_TYPE.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_TYPE.setPositionInForms(5)

assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_UNIT = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_VALUE_UNIT)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_UNIT.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_UNIT.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_VALUE_UNIT.setPositionInForms(6)

assignment_DATA_SET_TRANSCRIPTOMICS_SCALE = tr.assignPropertyType(data_set_type_TRANSCRIPTOMICS, prop_type_SCALE)
assignment_DATA_SET_TRANSCRIPTOMICS_SCALE.setMandatory(False)
assignment_DATA_SET_TRANSCRIPTOMICS_SCALE.setSection(None)
assignment_DATA_SET_TRANSCRIPTOMICS_SCALE.setPositionInForms(7)

assignment_DATA_SET_TSV_EXPORT_DATA_TYPE = tr.assignPropertyType(data_set_type_TSV_EXPORT, prop_type_DATA_TYPE)
assignment_DATA_SET_TSV_EXPORT_DATA_TYPE.setMandatory(False)
assignment_DATA_SET_TSV_EXPORT_DATA_TYPE.setSection(None)
assignment_DATA_SET_TSV_EXPORT_DATA_TYPE.setPositionInForms(1)

assignment_DATA_SET_TSV_MULTISTRAIN_EXPORT_DATA_TYPE = tr.assignPropertyType(data_set_type_TSV_MULTISTRAIN_EXPORT, prop_type_DATA_TYPE)
assignment_DATA_SET_TSV_MULTISTRAIN_EXPORT_DATA_TYPE.setMandatory(False)
assignment_DATA_SET_TSV_MULTISTRAIN_EXPORT_DATA_TYPE.setSection(None)
assignment_DATA_SET_TSV_MULTISTRAIN_EXPORT_DATA_TYPE.setPositionInForms(1)
