/*
 * Copyright 2011 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.generic.client.console;

import java.util.HashMap;
import java.util.Map;

import ch.systemsx.cisd.openbis.generic.shared.ICommonServer;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.SampleType;

/**
 * @author Pawel Glyzewski
 */
public class RegisterSampleType extends AbstractRegisterEntityType<SampleType> implements ICommand
{
    private enum SampleTypeAttributeSetter implements AttributeSetter<SampleType>
    {
        DESCRIPTION("description")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setDescription(value);
            }
        },

        LISTABLE("listable")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setListable(Boolean.parseBoolean(value));
            }
        },

        SHOW_CONTAINER("show-container")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setShowContainer(Boolean.parseBoolean(value));
            }
        },

        SHOW_PARENTS("show-parents")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setShowParents(Boolean.parseBoolean(value));
            }
        },

        UNIQUE_SUBCODES("unique-subcodes")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setSubcodeUnique(Boolean.parseBoolean(value));
            }
        },

        AUTO_GENERATE_CODES("auto-generate-codes")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setAutoGeneratedCode(Boolean.parseBoolean(value));
            }
        },

        GENERATED_CODES_PREFIX("generated-codes-prefix")
        {
            @Override
            public void setAttributeFor(SampleType sampleType, String value)
            {
                sampleType.setGeneratedCodePrefix(value);
            }

            @Override
            public void setDefaultFor(SampleType sampleType)
            {
                sampleType.setGeneratedCodePrefix("S");
            }
        };

        private final String attributeName;

        private SampleTypeAttributeSetter(String attributeName)
        {
            this.attributeName = attributeName;
        }

        @Override
        public String getAttributeName()
        {
            return attributeName;
        }

        @Override
        public void setDefaultFor(SampleType sampleType)
        {
        }
    }

    private static final Map<String, AttributeSetter<SampleType>> attributeSetters =
            new HashMap<String, AttributeSetter<SampleType>>();

    static
    {
        for (SampleTypeAttributeSetter setter : SampleTypeAttributeSetter.values())
        {
            attributeSetters.put(setter.getAttributeName(), setter);
        }
    }

    @Override
    protected Map<String, AttributeSetter<SampleType>> attributeSetters()
    {
        return attributeSetters;
    }

    @Override
    public void execute(ICommonServer server, String sessionToken, ScriptContext context,
            String argument)
    {
        server.registerSampleType(sessionToken, prepareEntityType(new SampleType(), argument));
    }
}
