/*
 * Copyright 2012 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.uitest.page;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.FindBys;

import ch.systemsx.cisd.openbis.uitest.infra.SampleType;

public class AddSampleTypeDialog extends Page
{

    @FindBy(id = "openbis_dialog-code-field-input")
    private WebElement code;

    @FindBy(id = "openbis_add-type-dialog-description-field-input")
    private WebElement description;

    @FindBy(id = "")
    private WebElement validationScript;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-listable"),
                @FindBy(xpath = "input") })
    private WebElement listable;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-show-container"),
                @FindBy(xpath = "input") })
    private WebElement showContainer;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-show-parents"),
                @FindBy(xpath = "input") })
    private WebElement showParents;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-subcode-unique"),
                @FindBy(xpath = "input") })
    private WebElement uniqueSubcodes;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-autogenerated-code"),
                @FindBy(xpath = "input") })
    private WebElement generateCodesAutomatically;

    @FindBys(
        {
                @FindBy(id = "openbis_add-type-dialog-show-parent-metadata"),
                @FindBy(xpath = "input") })
    private WebElement showParentMetadata;

    @FindBy(id = "openbis_add-type-dialog-generated-code-prefix")
    private WebElement generatedCodePrefix;

    @FindBy(id = "openbis_dialog-save-button")
    private WebElement saveButton;

    @FindBy(id = "openbis_dialog-cancel-button")
    private WebElement cancelButton;

    public SampleTypeBrowser save()
    {
        saveButton.click();
        return get(SampleTypeBrowser.class);
    }

    public AddSampleTypeDialog setCode(String code)
    {
        this.code.sendKeys(code);
        return this;
    }

    public AddSampleTypeDialog setListable(boolean checked)
    {
        setCheckBox(this.listable, checked);
        return this;
    }

    public AddSampleTypeDialog setShowContainer(boolean checked)
    {
        setCheckBox(this.showContainer, checked);
        return this;
    }

    public AddSampleTypeDialog setShowParents(boolean checked)
    {
        setCheckBox(this.showParents, checked);
        return this;
    }

    private void setCheckBox(WebElement element, boolean checked)
    {
        if (element.getAttribute("checked") != null ^ checked)
        {
            element.click();
        }
    }

    public void fillWith(SampleType sampleType)
    {
        setCode(sampleType.getCode());
        setListable(sampleType.isListable());
        setShowContainer(sampleType.isShowContainer());
        setShowParents(sampleType.isShowParents());
    }

}
