#! /bin/bash
# 2013, Chandrasekhar Ramakrishnan

SCRIPT="$0"
BINDIR="${SCRIPT%/*}"
LINK="`readlink $0`"
while [ -n "${LINK}" ]; do
  if [ "${LINK#/}" = "${LINK}" ]; then
    SCRIPT="${BINDIR}/${LINK}"
  else
    SCRIPT="${LINK}"
  fi
  LINK="`readlink ${SCRIPT}`"
done
#CONFLUENCE_CLI_ROOT="`dirname ${SCRIPT}`"
CONFLUENCE_CLI_ROOT="/usr/local/cisd/confluence_cli"

OPENBIS_PAGE=openBIS
SNAPSHOT_SPACE=openBISDoc1304

source ${CONFLUENCE_CLI_ROOT}/wiki.conf

PAGE="$1"

${CONFLUENCE_CLI_ROOT}/confluence --server https://wiki-bsse.ethz.ch --user ${USER} --password ${PASSWD} --space  ${SNAPSHOT_SPACE} --title "${PAGE}" --action getPageSource
