/*
 * Copyright 2017 ETH Zuerich, SIS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.update;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.common.update.FieldUpdateValue;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.common.update.ListUpdateValue.ListUpdateAction;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.IEntityTypeId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.update.IEntityTypeUpdate;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.update.PropertyAssignmentListUpdateValue;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.plugin.id.IPluginId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.space.id.ISpaceId;
import ch.systemsx.cisd.base.annotation.JsonObject;

/**
 * 
 *
 * @author Franz-Josef Elmer
 */
@JsonObject("as.dto.sample.update.SampleTypeUpdate")
public class SampleTypeUpdate implements IEntityTypeUpdate
{
    private static final long serialVersionUID = 1L;
    
    private IEntityTypeId typeId;
    
    private boolean autoGeneratedCode = false;

    private FieldUpdateValue<String> generatedCodePrefix = new FieldUpdateValue<String>();

    private boolean subcodeUnique = false;

    private FieldUpdateValue<String> description = new FieldUpdateValue<String>();

    private boolean listable = true;

    private boolean showContainer = false;

    private boolean showParents = true;

    private boolean showParentMetadata = false;

    private FieldUpdateValue<IPluginId> validationPluginId = new FieldUpdateValue<IPluginId>();
    
    @JsonProperty
    private PropertyAssignmentListUpdateValue propertyAssignments = new PropertyAssignmentListUpdateValue();

    @Override
    public IEntityTypeId getTypeId()
    {
        return typeId;
    }

    @Override
    public void setTypeId(IEntityTypeId typeId)
    {
        this.typeId = typeId;
    }

    public boolean isAutoGeneratedCode()
    {
        return autoGeneratedCode;
    }

    public void setAutoGeneratedCode(boolean autoGeneratedCode)
    {
        this.autoGeneratedCode = autoGeneratedCode;
    }

    public FieldUpdateValue<String> getGeneratedCodePrefix()
    {
        return generatedCodePrefix;
    }

    public void setGeneratedCodePrefix(String generatedCodePrefix)
    {
        this.generatedCodePrefix.setValue(generatedCodePrefix);
    }

    public boolean isSubcodeUnique()
    {
        return subcodeUnique;
    }

    public void setSubcodeUnique(boolean subcodeUnique)
    {
        this.subcodeUnique = subcodeUnique;
    }

    @Override
    public FieldUpdateValue<String> getDescription()
    {
        return description;
    }

    @Override
    public void setDescription(String description)
    {
        this.description.setValue(description);
    }

    public boolean isListable()
    {
        return listable;
    }

    public void setListable(boolean listable)
    {
        this.listable = listable;
    }

    public boolean isShowContainer()
    {
        return showContainer;
    }

    public void setShowContainer(boolean showContainer)
    {
        this.showContainer = showContainer;
    }

    public boolean isShowParents()
    {
        return showParents;
    }

    public void setShowParents(boolean showParents)
    {
        this.showParents = showParents;
    }

    public boolean isShowParentMetadata()
    {
        return showParentMetadata;
    }

    public void setShowParentMetadata(boolean showParentMetadata)
    {
        this.showParentMetadata = showParentMetadata;
    }

    @Override
    public FieldUpdateValue<IPluginId> getValidationPluginId()
    {
        return validationPluginId;
    }

    @Override
    public void setValidationPluginId(IPluginId validationPluginId)
    {
        this.validationPluginId.setValue(validationPluginId);
    }

    @Override
    public IEntityTypeId getObjectId()
    {
        return getTypeId();
    }

    @Override
    public PropertyAssignmentListUpdateValue getPropertyAssignments()
    {
        return propertyAssignments;
    }

    @Override
    public void setPropertyAssignmentActions(List<ListUpdateAction<Object>> actions)
    {
        propertyAssignments.setActions(actions);
    }

}
