#!/bin/bash

BUSTARD=$1
SRF_DIR=Srf_RTA

[ -d $SRF_DIR ] || mkdir $SRF_DIR
for a in 1 2 3 4 5 6 7 8; do
  echo Converting Lane $a to SRF
  time /dsf/illumina2srf -b -o $SRF_DIR/s_${a}_RTA.srf $BUSTARD/s_${a}_*_qseq.txt ;
done
