#!/bin/bash

export BUSTARD=$1
export NUMBER_OF_LANES=$2
export SRF_DIR=Srf_RTA
export ILLUMINA2SRF=/usr/local/dsu/bin/illumina2srf

export PRG=`basename $0`
export USAGE="Usage: ${PRG} <Path_to_Bustard_Folder> <Number_of_Lanes> \n\nEXAMPLE: ${PRG} /array0/Runs/090720_42HUDAAXX/Data/Intensities/Bustard/ 8" 

if [ -z "${BUSTARD}"  -o -z "${NUMBER_OF_LANES}" ]
then
   echo "${USAGE}"
   exit 1
fi

[ -d $SRF_DIR ] || mkdir $SRF_DIR
for  (( a=1; a<=$NUMBER_OF_LANES; a++ )); do
  echo Converting Lane $a to SRF
  $ILLUMINA2SRF -b -o $SRF_DIR/s_${a}.srf $BUSTARD/s_${a}_*_qseq.txt &
done