#!/bin/bash

export BUSTARD=$1
export SRF_DIR=Srf_RTA
export ILLUMINA2SRF=/usr/local/dsu/bin/illumina2srf

[ -d $SRF_DIR ] || mkdir $SRF_DIR
for a in 1 2 3 4 5 6 7 8; do
  echo Converting Lane $a to SRF
  $ILLUMINA2SRF -b -o $SRF_DIR/s_${a}_RTA.srf $BUSTARD/s_${a}_*_qseq.txt ;
done
