import SelectField from '@src/js/components/common/form/SelectField.jsx'
import TextField from '@src/js/components/common/form/TextField.jsx'
import CheckboxField from '@src/js/components/common/form/CheckboxField.jsx'
import CheckboxFieldWrapper from '@srcTest/js/components/common/form/wrapper/CheckboxFieldWrapper.js'
import TextFieldWrapper from '@srcTest/js/components/common/form/wrapper/TextFieldWrapper.js'
import SelectFieldWrapper from '@srcTest/js/components/common/form/wrapper/SelectFieldWrapper.js'
import PageParametersPanelWrapper from '@srcTest/js/components/common/page/wrapper/PageParametersPanelWrapper'

export default class TypeFormParametersTypeWrapper extends PageParametersPanelWrapper {
  getCode() {
    return new TextFieldWrapper(
      this.findComponent(TextField).filter({ name: 'code' })
    )
  }

  getDescription() {
    return new TextFieldWrapper(
      this.findComponent(TextField).filter({ name: 'description' })
    )
  }

  getValidationPlugin() {
    return new SelectFieldWrapper(
      this.findComponent(SelectField).filter({ name: 'validationPlugin' })
    )
  }

  getAutoGeneratedCode() {
    return new CheckboxFieldWrapper(
      this.findComponent(CheckboxField).filter({ name: 'autoGeneratedCode' })
    )
  }

  getGeneratedCodePrefix() {
    return new TextFieldWrapper(
      this.findComponent(TextField).filter({ name: 'generatedCodePrefix' })
    )
  }

  toJSON() {
    return {
      ...super.toJSON(),
      code: this.getCode().toJSON(),
      description: this.getDescription().toJSON(),
      validationPlugin: this.getValidationPlugin().toJSON(),
      autoGeneratedCode: this.getAutoGeneratedCode().toJSON(),
      generatedCodePrefix: this.getGeneratedCodePrefix().toJSON()
    }
  }
}
