    
ALTER TABLE COLUMN_VALUES DROP CONSTRAINT COLUMNS_COLUMN_VALUES;
ALTER TABLE COLUMN_VALUES ADD CONSTRAINT COLUMNS_COLUMN_VALUES 
    FOREIGN KEY (COLU_ID) REFERENCES COLUMNS (ID) ON DELETE CASCADE;

ALTER TABLE DATA_COLUMNS DROP CONSTRAINT DATA_SETS_DATA_COLUMNS;
ALTER TABLE DATA_COLUMNS ADD CONSTRAINT DATA_SETS_DATA_COLUMNS 
    FOREIGN KEY (DASE_ID) REFERENCES DATA_SETS (ID) ON DELETE CASCADE;
    
ALTER TABLE DATA_COLUMN_VALUES DROP CONSTRAINT DATA_COLUMNS_DATA_COLUMN_VALUES; 
ALTER TABLE DATA_COLUMN_VALUES ADD CONSTRAINT DATA_COLUMNS_DATA_COLUMN_VALUES 
    FOREIGN KEY (DACO_ID) REFERENCES DATA_COLUMNS (ID) ON DELETE CASCADE;
    
ALTER TABLE COLUMNS DROP CONSTRAINT DATA_SETS_COLUMNS;
ALTER TABLE COLUMNS ADD CONSTRAINT DATA_SETS_COLUMNS 
    FOREIGN KEY (DASE_ID) REFERENCES DATA_SETS (ID) ON DELETE CASCADE;

    