/*
 * Copyright 2009 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.yeastx.fiaml;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.ResultColumn;

/**
 * 
 *
 * @author Bernd Rinn
 */
public class CentroidDTO
{

    @AutoGeneratedKeys
    @ResultColumn("CENTROID_ID")
    private long centroidId;
    
    @ResultColumn("FIA_MS_RUN_ID")
    private long fiaMsRunId;

    public long getCentroidId()
    {
        return centroidId;
    }

    public void setCentroidId(long centroidId)
    {
        this.centroidId = centroidId;
    }

    public long getFiaMsRunId()
    {
        return fiaMsRunId;
    }

    public void setFiaMsRunId(long fiaMsRunId)
    {
        this.fiaMsRunId = fiaMsRunId;
    }

    
}
