/*
 * Copyright 2009 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.yeastx.fiaml;

import java.util.Date;

import net.lemnik.eodsql.AutoGeneratedKeys;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * A class that represents a MSRun in an eicML file.
 */
public class FIAMSRunDTO
{
    @AutoGeneratedKeys
    private long fiaMsRunId;

    private String permId;
    
    private String rawDataFilePath;

    private String rawDataFileName;

    private String instrumentType;

    private String instrumentManufacturer;

    private String instrumentModel;

    private String methodIonisation;

    private String methodSeparation;

    private char polarity = '?';

    private Date acquisitionDate;
    
    private float lowMz;
    
    private float highMz;
    
    private float internalStandard;
    
    private float od;
    
    private String operator;

    public String getPermId()
    {
        return permId;
    }

    public void setPermId(String permId)
    {
        this.permId = permId;
    }

    public long getFiaMsRunId()
    {
        return fiaMsRunId;
    }

    public void setFiaMsRunId(long eicMsRunId)
    {
        this.fiaMsRunId = eicMsRunId;
    }

    public String getRawDataFilePath()
    {
        return rawDataFilePath;
    }

    public void setRawDataFilePath(String rawDataFilePath)
    {
        this.rawDataFilePath = rawDataFilePath;
    }

    public String getRawDataFileName()
    {
        return rawDataFileName;
    }

    public void setRawDataFileName(String rawDataFileName)
    {
        this.rawDataFileName = rawDataFileName;
    }

    public String getInstrumentType()
    {
        return instrumentType;
    }

    public void setInstrumentType(String instrumentType)
    {
        this.instrumentType = instrumentType;
    }

    public String getInstrumentManufacturer()
    {
        return instrumentManufacturer;
    }

    public void setInstrumentManufacturer(String instrumentManufacturer)
    {
        this.instrumentManufacturer = instrumentManufacturer;
    }

    public String getInstrumentModel()
    {
        return instrumentModel;
    }

    public void setInstrumentModel(String instrumentModel)
    {
        this.instrumentModel = instrumentModel;
    }

    public String getMethodIonisation()
    {
        return methodIonisation;
    }

    public void setMethodIonisation(String methodIonisation)
    {
        this.methodIonisation = methodIonisation;
    }

    public String getMethodSeparation()
    {
        return methodSeparation;
    }

    public void setMethodSeparation(String methodSeparation)
    {
        this.methodSeparation = methodSeparation;
    }

    public void setPolarity(char polarity)
    {
        this.polarity = polarity;
    }

    public char getPolarity()
    {
        return polarity;
    }

    public Date getAcquisitionDate()
    {
        return acquisitionDate;
    }

    public void setAcquisitionDate(Date acquisitionDate)
    {
        this.acquisitionDate = acquisitionDate;
    }

    public String getOperator()
    {
        return operator;
    }

    public void setOperator(String operator)
    {
        this.operator = operator;
    }

    public float getLowMz()
    {
        return lowMz;
    }

    public void setLowMz(float lowMz)
    {
        this.lowMz = lowMz;
    }

    public float getHighMz()
    {
        return highMz;
    }

    public void setHighMz(float highMz)
    {
        this.highMz = highMz;
    }

    public float getInternalStandard()
    {
        return internalStandard;
    }

    public void setInternalStandard(float internalStandard)
    {
        this.internalStandard = internalStandard;
    }

    public float getOd()
    {
        return od;
    }

    public void setOd(float od)
    {
        this.od = od;
    }

    @Override
    public String toString()
    {
        return ToStringBuilder.reflectionToString(this);
    }
}