/*
 * Copyright 2008 ETH Zuerich, CISD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.systemsx.cisd.openbis.plugin.generic.client.web.client.application.sample;

import java.util.List;

import ch.systemsx.cisd.common.shared.basic.utils.StringUtils;
import ch.systemsx.cisd.openbis.generic.client.web.client.application.ActionContext;
import ch.systemsx.cisd.openbis.generic.client.web.client.application.IViewContext;
import ch.systemsx.cisd.openbis.generic.client.web.client.application.ui.AbstractRegistrationForm;
import ch.systemsx.cisd.openbis.generic.client.web.client.application.ui.GroupSelectionWidget;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.IEntityProperty;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.NewSample;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.SampleType;
import ch.systemsx.cisd.openbis.generic.shared.basic.dto.Space;
import ch.systemsx.cisd.openbis.plugin.generic.client.web.client.IGenericClientServiceAsync;

/**
 * The <i>generic</i> sample registration form.
 * 
 * @author Izabela Adamczyk
 */
public final class GenericSampleRegistrationForm extends AbstractGenericSampleRegisterEditForm
{
    public GenericSampleRegistrationForm(
            final IViewContext<IGenericClientServiceAsync> viewContext,
            final SampleType sampleType, ActionContext actionContext)
    {
        super(viewContext, actionContext);
        this.sampleType = sampleType;
    }

    @Override
    protected void resetFieldsAfterSave()
    {
        codeField.reset();
        attachmentsManager.resetAttachmentFieldSetsInPanel(formPanel);
    }

    // public only for tests
    public final class RegisterSampleCallback extends
            AbstractRegistrationForm.AbstractRegistrationCallback<Void>
    {
        public RegisterSampleCallback(IViewContext<?> viewContext)
        {
            super(viewContext);
        }

        @Override
        protected String createSuccessfullRegistrationInfo(Void result)
        {
            String code = codeField.getValue();
            final Space selectedGroup = groupSelectionWidget.tryGetSelectedGroup();
            boolean shared = GroupSelectionWidget.isSharedGroup(selectedGroup);
            if (shared)
            {
                return "Shared sample <b>" + code + "</b> successfully registered";

            } else
            {
                return "Sample <b>" + code + "</b> successfully registered in space <b>"
                        + selectedGroup.getCode() + "</b>";
            }
        }
    }

    @Override
    protected void initializeFormFields()
    {
        propertiesEditor.initWithoutProperties(sampleType.getAssignedPropertyTypes());
    }

    @Override
    protected void loadForm()
    {
        initGUI();
    }

    @Override
    protected void save()
    {
        String experimentIdentifier =
                (experimentField != null && experimentField.tryToGetValue() != null) ? experimentField
                        .tryToGetValue().getIdentifier()
                        : null;

        final String containerOrNull = StringUtils.trimToNull(container.getValue());
        final String parentOrNull = StringUtils.trimToNull(parent.getValue());
        final NewSample newSample;
        if (parentOrNull == null)
        {
            final String[] parents = getParents();
            newSample =
                    NewSample.createWithParents(createSampleIdentifier(), sampleType,
                            containerOrNull, parents);
        } else
        {
            newSample =
                    NewSample.createWithParent(createSampleIdentifier(), sampleType,
                            containerOrNull, parentOrNull);
        }
        final List<IEntityProperty> properties = extractProperties();
        newSample.setProperties(properties.toArray(IEntityProperty.EMPTY_ARRAY));
        newSample.setAttachments(attachmentsManager.extractAttachments());
        newSample.setExperimentIdentifier(experimentIdentifier);
        viewContext.getService().registerSample(attachmentsSessionKey, newSample,
                new RegisterSampleCallback(viewContext));
    }

    @Override
    protected boolean isAutoGenerateCode()
    {
        return sampleType.isAutoGeneratedCode();
    }

}
