#!/usr/bin/env python
# -*- coding: utf-8 -*-

import ch.systemsx.cisd.openbis.generic.server.jython.api.v1.DataType as DataType

numberOfStorageGroups = 15
stogageGroupPropertyCodes = ["STORAGE_NAME", "STORAGE_ROW", "STORAGE_COLUMN", "STORAGE_BOX_NAME", "STORAGE_USER", "STORAGE_BOX_POSITION"] #This is duplicated below, needs cleanup
storageGroupDefinition = [
    ["STORAGE_NAME_0",         "Physical Storage 0",        "location",         DataType.CONTROLLEDVOCABULARY,      "FREEZER",            "Storage Name 0",       None],
    ["STORAGE_ROW_0",          "Physical Storage 0",        "Storage Row",      DataType.INTEGER,                    None,                "Storage Row 0",        None],
    ["STORAGE_COLUMN_0",       "Physical Storage 0",        "Storage Column",   DataType.INTEGER,                    None,                "Storage Column 0",     None],
    ["STORAGE_BOX_NAME_0",     "Physical Storage 0",        "box label",        DataType.VARCHAR,                    None,                "Storage Box Name 0",   None],
    ["STORAGE_USER_0",         "Physical Storage 0",        "frozen by",        DataType.CONTROLLEDVOCABULARY,      "ALL_LAB_MEMBERS",    "Storage User Id 0",    None],
    ["STORAGE_BOX_POSITION_0", "Physical Storage 0",        "position",         DataType.VARCHAR,                    None,                "Storage Box Position 0",    None]
];

def getVocaularyTermCodeForVocabularyAndTermLabel(vocabularyCode, termLabel):
    vocabulary = vocacbularyDefinitions[vocabularyCode]
    for term in vocabulary:
        if term[1] == termLabel:
            #print repr("NOT FOUND: " + unicode(vocabularyCode) + " : '" + unicode(termLabel) + "'")
            return term[0]
    return None
    
def getPropertyDefinitionByCode(definition, code):
    for property in definition:
        if property[0] == code:
            return property
    return None

antibodyDefinition = [
    ["NAME",                           "General",                "antibody ID",                        DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_ID_NR",                 "General",                "antibody_id_nr",                     DataType.VARCHAR,                    None,  "", None],
    ["ANTIGEN",                        "General",                "antigen",                            DataType.VARCHAR,                    None,  "", None],
    ["BARCODE",                        "General",                "barcode",                            DataType.VARCHAR,                    None,  "", None],
    ["BARCODE_LABEL",                  "General",                "barcode label",                      DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_FACS_BLOCK",            "General",                "block facs",                         DataType.CONTROLLEDVOCABULARY,       "BLOCK",  "", None],
    ["ANTIBODY_IF_BLOCK",              "General",                "block IFF",                          DataType.CONTROLLEDVOCABULARY,       "BLOCK",  "", None],
    ["ANTIBODY_WB_BLOCK",              "General",                "block western",                      DataType.CONTROLLEDVOCABULARY,       "BLOCK",  "", None],
    ["BOX",                            "General",                "box",                                DataType.VARCHAR,                    None,  "", None],
    ["CATALOGUE_NUMBER",               "General",                "catalog id #",                       DataType.VARCHAR,                    None,  "", None],
    ["CLASS",                          "General",                "class",                              DataType.CONTROLLEDVOCABULARY,       "CLASS",  "", None],
    ["CLONE",                          "General",                "clone",                              DataType.VARCHAR,                    None,  "", None],
    ["COMPANY",                        "General",                "company",                            DataType.CONTROLLEDVOCABULARY,       "COMPANY",  "", None],
    ["ANTIBODY_FACS_CONC",             "General",                "conc facs",                          DataType.CONTROLLEDVOCABULARY,       "CONCENTRATION_FACS",  "", None],
    ["ANTIBODY_IF_CONC",               "General",                "conc IFF",                           DataType.CONTROLLEDVOCABULARY,       "CONCENTRATION_FACS",  "", None],
    ["ANTIBODY_IP_CONC",               "General",                "conc ip",                            DataType.CONTROLLEDVOCABULARY,       "CONCENTRATION_IP",  "", None],
    ["ANTIBODY_WB_CONC",               "General",                "conc western",                       DataType.CONTROLLEDVOCABULARY,       "CONCENTRATION_WESTERN",  "", None],
    ["ANTIBODY_CONCENTRATION",         "General",                "concentration",                      DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_CROSSREACTIVITY",       "General",                "crossreactivity",                    DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_FACS_FIX",              "General",                "fix facs",                           DataType.CONTROLLEDVOCABULARY,       "FIX",  "", None],
    ["ANTIBODY_IF_FIX",                "General",                "fix IFF",                            DataType.CONTROLLEDVOCABULARY,       "FIX",  "", None],
    ["ANTIBODY_WB_FIX",                "General",                "fix western",                        DataType.CONTROLLEDVOCABULARY,       "FIX",  "", None],
    ["COMMENTS",                       "Comments",               "info",                               DataType.VARCHAR,                    None,  "", None],
    ["INVESTIGATOR",                   "General",                "investigator",                       DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["LABEL",                          "General",                "label",                              DataType.CONTROLLEDVOCABULARY,       "LABEL",  "", None],
    ["LOTNUMBER",                      "General",                "lotnumber",                          DataType.VARCHAR,                    None,  "", None],
    ["MODIFIED_BY",                    "General",                "modified by",                        DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["MONO_POLYCLONAL",                "General",                "mono/polyclonal",                    DataType.CONTROLLEDVOCABULARY,       "MONO-POLYCLONAL",  "", None],
    ["ANTIBODY_FACS_NOTES",            "General",                "notes FACS",                         DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_IF_NOTES",              "General",                "notes IFF",                          DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_IP_NOTES",              "General",                "notes IP",                           DataType.VARCHAR,                    None,  "", None],
    ["ANTIBODY_WB_NOTES",              "General",                "notes western",                      DataType.VARCHAR,                    None,  "", None],
    ["RACK",                           "General",                "rack",                               DataType.VARCHAR,                    None,  "", None],
    ["PUBLISHED_IN",                   "Reference",              "reference",                          DataType.VARCHAR,                    None,  "", None],
    ["SERIAL_NUMBER",                  "General",                "serial number",                      DataType.INTEGER,                    None,  "", None],
    ["ANTIGEN_SIZE",                   "General",                "size",                               DataType.VARCHAR,                    None,  "", None],
    ["SOURCE",                         "General",                "source",                             DataType.CONTROLLEDVOCABULARY,       "SOURCE",  "", None],
    ["CREATION_DATE",                  "General",                "creation date",                      DataType.TIMESTAMP,                  None,  "", None],
    ["MODIFICATION_DATE",              "General",                "modification date",                  DataType.TIMESTAMP,                  None,  "", None],
    ["FROZEN",                         "General",                "frozen",                             DataType.TIMESTAMP,                  None,  "", None]
];


cellDefinition = [
    ["CO2",                            "General",                "%CO2",                               DataType.CONTROLLEDVOCABULARY,       "CO2",  "", None],
    ["ATCC_NUM",                       "General",                "ATCC No.",                           DataType.VARCHAR,                    None,  "", None],
    ["BARCODE",                        "General",                "barcode",                            DataType.VARCHAR,                    None,  "", None],
    ["BARCODE_LABEL",                  "General",                "barcode label",                      DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_NR",                     "General",                "cell_id_nr",                         DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_NR_COPY",                "General",                "cell_id_nr Copy",                    DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID",                        "General",                "cell ID",                            DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_COPY",                   "General",                "cell ID Copy",                       DataType.VARCHAR,                    None,  "", None],
    ["CLONE",                          "General",                "clone #",                            DataType.INTEGER,                    None,  "", None],
    ["COMPARE_FIELD",                  "General",                "compare field",                      DataType.VARCHAR,                    None,  "", None],
    ["CONC1",                          "General",                "conc.1",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT1",                     "General",                "concentration unit 1",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC2",                          "General",                "conc.2",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT2",                     "General",                "concentration unit 2",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC3",                          "General",                "conc.3",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT3",                     "General",                "concentration unit 3",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC4",                          "General",                "conc.4",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT4",                     "General",                "concentration unit 4",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CREATION_DATE",                  "General",                "creation date",                      DataType.TIMESTAMP,                  None,  "", None],
    ["DATE",                           "General",                "date",                               DataType.TIMESTAMP,                  None,  "", None],
    ["FROZEN",                         "General",                "frozen",                             DataType.TIMESTAMP,                  None,  "", None],
    ["GROWTH_TEMPERATURE",             "General",                "growth temperature",                 DataType.CONTROLLEDVOCABULARY,       "GROWTH_TEMPERATURE",  "", None],
    ["INVESTIGATOR",                   "General",                "investigator",                       DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["COMMENTS",                       "Comments",               "info",                               DataType.VARCHAR,                    None,  "", None],
    ["LINE_NAME",                      "General",                "line name",                          DataType.VARCHAR,                    None,  "", None],
    ["MEDIUM",                         "General",                "medium",                             DataType.CONTROLLEDVOCABULARY,       "MEDIUM",  "", None],
    ["MEDIUM_SPECIALS",                "General",                "medium specials",                    DataType.VARCHAR,                    None,  "", None],
    ["MODIFICATION_DATE",              "General",                "modification date",                  DataType.TIMESTAMP,                  None,  "", None],
    ["MODIFIED_BY",                    "General",                "modified by",                        DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["MYCOPLASM_TESTED",               "General",                "mycoplasm_tested",                   DataType.BOOLEAN,                    None,  "", None],
    ["OBTAINED_FROM",                  "General",                "obtained from",                      DataType.CONTROLLEDVOCABULARY,       "CELL_OBTAINED_FROM",  "", None],
    ["PAGE_NUMBER",                    "General",                "page number",                        DataType.VARCHAR,                    None,  "", None],
    ["PARENTAL_CELL",                  "General",                "parental cell",                      DataType.VARCHAR,                    None,  "", None],
    ["PASSAGE",                        "General",                "passage",                            DataType.VARCHAR,                    None,  "", None],
    ["PERS_CELL_NUMBER",               "General",                "PersCellNumber",                     DataType.VARCHAR,                    None,  "", None],
    ["PLASMID_ID1",                    "General",                "plasmid ID 1",                       DataType.VARCHAR,                    None,  "", None],
    ["PLASMID_ID2",                    "General",                "plasmid ID 2",                       DataType.VARCHAR,                    None,  "", None],
    ["PUBLISHED_IN",                   "Reference",              "reference",                          DataType.VARCHAR,                    None,  "", None],
    ["SELECTION_PLASMID1",             "General",                "sel.1",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SELECTION_PLASMID2",             "General",                "sel.2",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SELECTION_PLASMID3",             "General",                "sel.3",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],    
    ["SELECTION_PLASMID4",             "General",                "sel.4",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SERIAL_NUMBER",                  "General",                "serial number",                      DataType.INTEGER,                    None,  "", None],
    ["SPECIES",                        "General",                "species",                            DataType.CONTROLLEDVOCABULARY,       "CELL_SPECIES",  "", None],
    ["VIRUS_ID1",                      "General",                "virus ID 1",                         DataType.VARCHAR,                    None,  "", None],
    ["VIRUS_ID2",                      "General",                "virus ID 2",                         DataType.VARCHAR,                    None,  "", None]
];

strainDefinition = [
    ["CO2",                            "General",                "%CO2",                               DataType.CONTROLLEDVOCABULARY,       "CO2",  "", None],
    ["ATCC_NUM",                       "General",                "ATCC No.",                           DataType.VARCHAR,                    None,  "", None],
    ["BARCODE",                        "General",                "barcode",                            DataType.VARCHAR,                    None,  "", None],
    ["BARCODE_LABEL",                  "General",                "barcode label",                      DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_NR",                     "General",                "cell_id_nr",                         DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_NR_COPY",                "General",                "cell_id_nr Copy",                    DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID",                        "General",                "cell ID",                            DataType.VARCHAR,                    None,  "", None],
    ["CELL_ID_COPY",                   "General",                "cell ID Copy",                       DataType.VARCHAR,                    None,  "", None],
    ["CLONE",                          "General",                "clone #",                            DataType.INTEGER,                    None,  "", None],
    ["COMPARE_FIELD",                  "General",                "compare field",                      DataType.VARCHAR,                    None,  "", None],
    ["CONC1",                          "General",                "conc.1",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT1",                     "General",                "concentration unit 1",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC2",                          "General",                "conc.2",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT2",                     "General",                "concentration unit 2",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC3",                          "General",                "conc.3",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT3",                     "General",                "concentration unit 3",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CONC4",                          "General",                "conc.4",                             DataType.REAL,                       None,  "", None],
    ["CONC_UNIT4",                     "General",                "concentration unit 4",               DataType.CONTROLLEDVOCABULARY,       "CONC_UNITS",  "", None],
    ["CREATION_DATE",                  "General",                "creation date",                      DataType.TIMESTAMP,                  None,  "", None],
    ["DATE",                           "General",                "date",                               DataType.TIMESTAMP,                  None,  "", None],
    ["FROZEN",                         "General",                "frozen",                             DataType.TIMESTAMP,                  None,  "", None],
    ["GROWTH_TEMPERATURE",             "General",                "growth temperature",                 DataType.CONTROLLEDVOCABULARY,       "GROWTH_TEMPERATURE",  "", None],
    ["INVESTIGATOR",                   "General",                "investigator",                       DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["COMMENTS",                       "Comments",               "info",                               DataType.VARCHAR,                    None,  "", None],
    ["LINE_NAME",                      "General",                "line name",                          DataType.VARCHAR,                    None,  "", None],
    ["MEDIUM",                         "General",                "medium",                             DataType.CONTROLLEDVOCABULARY,       "MEDIUM",  "", None],
    ["MEDIUM_SPECIALS",                "General",                "medium specials",                    DataType.VARCHAR,                    None,  "", None],
    ["MODIFICATION_DATE",              "General",                "modification date",                  DataType.TIMESTAMP,                  None,  "", None],
    ["MODIFIED_BY",                    "General",                "modified by",                        DataType.CONTROLLEDVOCABULARY,       "ALL_LAB_MEMBERS",  "", None],
    ["MYCOPLASM_TESTED",               "General",                "mycoplasm_tested",                   DataType.BOOLEAN,                    None,  "", None],
    ["OBTAINED_FROM",                  "General",                "obtained from",                      DataType.CONTROLLEDVOCABULARY,       "CELL_OBTAINED_FROM",  "", None],
    ["PAGE_NUMBER",                    "General",                "page number",                        DataType.VARCHAR,                    None,  "", None],
    ["PARENTAL_CELL",                  "General",                "parental cell",                      DataType.VARCHAR,                    None,  "", None],
    ["PASSAGE",                        "General",                "passage",                            DataType.VARCHAR,                    None,  "", None],
    ["PERS_CELL_NUMBER",               "General",                "PersCellNumber",                     DataType.VARCHAR,                    None,  "", None],
    ["PLASMID_ID1",                    "General",                "plasmid ID 1",                       DataType.VARCHAR,                    None,  "", None],
    ["PLASMID_ID2",                    "General",                "plasmid ID 2",                       DataType.VARCHAR,                    None,  "", None],
    ["PUBLISHED_IN",                   "Reference",              "reference",                          DataType.VARCHAR,                    None,  "", None],
    ["SELECTION_PLASMID1",             "General",                "sel.1",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SELECTION_PLASMID2",             "General",                "sel.2",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SELECTION_PLASMID3",             "General",                "sel.3",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],    
    ["SELECTION_PLASMID4",             "General",                "sel.4",                              DataType.CONTROLLEDVOCABULARY,       "SELECTION",  "", None],
    ["SERIAL_NUMBER",                  "General",                "serial number",                      DataType.INTEGER,                    None,  "", None],
    ["SPECIES",                        "General",                "species",                            DataType.CONTROLLEDVOCABULARY,       "CELL_SPECIES",  "", None],
    ["VIRUS_ID1",                      "General",                "virus ID 1",                         DataType.VARCHAR,                    None,  "", None],
    ["VIRUS_ID2",                      "General",                "virus ID 2",                         DataType.VARCHAR,                    None,  "", None]
];


vocacbularyDefinitions = {
                          "ALL_LAB_MEMBERS" : [
                                        ["ANNA_DEPLAZES",   "Anna Deplazes"],
                                        ["ANNE-CHRISTINE_BUTTY",   "Anne-Christine Butty"],
                                        ["BRIAN_LUKE",   "Brian Luke"],
                                        ["CAROLINE_ZBINDEN",   "Caroline Zbinden"],
                                        ["CELINE_LAFOURCADE",   "Celine Lafourcade"],
                                        ["CHRISTINE_RUPP",   "Christine Rupp"],
                                        ["CLAUDINE_KRAFT",   "Claudine Kraft"],
                                        ["EDYTA_SIERGIEJUK",   "Edyta Siergiejuk"],
                                        ["FABIAN_HERZOG",   "Fabian Herzog"],
                                        ["FABIAN_RUDOLF",   "Fabian Rudolf"],
                                        ["FRANK_VAN_DROGEN",   "Frank Van Drogen"],
                                        ["GERDA_JORRITSMA",   "Gerda Jorritsma"],
                                        ["GWEN_RABUT",   "Gw\xe9nael Rabut"],
                                        ["INGRID_STOFFEL-STUDER",   "Ingrid Stoffel-Studer"],
                                        ["IRAM_ZAIDI",   "Iram Zaidi"],
                                        ["IZABELA_SUMARA",   "Izabela Sumara"],
                                        ["LIONEL_PINTARD",   "Lionel Pintard"],
                                        ["MALIKAJAQUENOUD",   "MalikaJaquenoud"],
                                        ["MARC_SOHRMANN",   "Marc Sohrmann"],
                                        ["MARIE-LYN_HECHT",   "Marie-Lyn Hecht"],
                                        ["MARIE-PIERRE_GULLI",   "Marie-Pierre Gulli"],
                                        ["MATTHIAS_PETER",   "Matthias Peter"],
                                        ["MICHAEL_OLMA",   "Michael Olma"],
                                        ["MICHAEL_SCHNEIDER",   "Michael Schneider"],
                                        ["MICHELE_KNAUS",   "Michele Knaus"],
                                        ["MONIKA_GERSBACH",   "Monika Gersbach"],
                                        ["NATHALIE_MEYER-SCHALLER",   "Nathalie Meyer-Schaller"],
                                        ["NATHALIE_PERRINJAQUET",   "Nathalie Perrinjaquet"],
                                        ["NICOLAS_DARD",   "Nicolas Dard"],
                                        ["NICOLAS_PAGE",   "Nicolas Page"],
                                        ["PATRICK_PEDRIOLI",   "Patrick Pedrioli"],
                                        ["PHILIPPE_WIGET",   "Philippe Wiget"],
                                        ["PIERRE_MAILLARD",   "Pierre Maillard"],
                                        ["REINHARD_DECHANT",   "Reinhard Dechant"],
                                        ["SANDER_SPRINGER",   "Sander Springer"],
                                        ["SARAH_GLASER",   "Sarah Glaser"],
                                        ["SARAH_MAERKI",   "Sarah  M\xe4rki"],
                                        ["SEBASTIAN_LEIDEL",   "Sebastian Leidel"],
                                        ["SERGE_PELET",   "Serge Pelet"],
                                        ["STEFAN_MUELLER",   "Stefan M�ller"],
                                        ["TANIA_ROBERTS",   "Tania Roberts"],
                                        ["THIMO_KURZ",   "Thimo Kurz"],
                                        ["TOBIAS_BRAUN",   "Tobias Braun"],
                                        ["VANESSA_REZGUI",   "Vanessa Rezgui"],
                                        ["WOJCIECH_PIWKO",   "Wojciech Piwko"],
                                        ["YUKIKO_SHIMADA",   "Yukiko Shimada"],
                                        ["YVONNE_GLOOR",   "Yvonne Gloor"],
                                        ["JOCHEN_BECK",   "Jochen Beck"],
                                        ["MONIKA_KIJANSKA",   "Monika Kijanska"],
                                        ["ANGIE_RAGHEB",   "Angie Ragheb"],
                                        ["ANNE_PACQUELET",   "Anne Pacquelet"],
                                        ["BJORN_HEGEMANN",   "Bj\xf6rn Hegemann"],
                                        ["JANNY_TILMA",   "Janny Tilma"],
                                        ["THIBAULT_COURTHEOUX",   "Thibault Courtheoux"],
                                        ["SAMUEL_GILBERTO",   "Samuel Gilberto"],
                                        ["REMY_BUSER",   "Remy Buser"],
                                        ["RADOSLAV_ENCHEV",   "Radoslav Enchev"],
                                        ["MICHAELA_HUBNER",   "Michaela Hubner"],
                                        ["MIA_LI",   "Mia Li"],
                                        ["JULIEN_MOUYSSET",   "Julien Mouysset"]
                                    ],
                           "LAB_MEMBERS_INITIALS" : [
                                        ["AD", "AD"],
                                        ["ACB", "ACB"],
                                        ["BL", "BL"],
                                        ["CZ", "CZ"],
                                        ["CL", "CL"],
                                        ["CR", "CR"],
                                        ["CK", "CK"],
                                        ["ES", "ES"],
                                        ["FH", "FH"],
                                        ["FR", "FR"],
                                        ["FD", "FD"],
                                        ["GJ", "GJ"],
                                        ["GR", "GR"],
                                        ["ISS", "ISS"],
                                        ["IZ", "IZ"],
                                        ["IS", "IS"],
                                        ["LP", "LP"],
                                        ["MJ", "MJ"],
                                        ["MSO", "MSo"],
                                        ["MH", "MH"],
                                        ["MG", "MG"],
                                        ["MP", "MP"],
                                        ["MO", "MO"],
                                        ["MSC", "MSc"],
                                        ["MK", "MK"],
                                        ["MG", "MG"],
                                        ["NS", "NS"],
                                        ["NPE", "NPe"],
                                        ["ND", "ND"],
                                        ["NPA", "NPa"],
                                        ["PP", "PP"],
                                        ["PW", "PW"],
                                        ["PM", "PM"],
                                        ["RD", "RD"],
                                        ["SS", "SS"],
                                        ["SG", "SG"],
                                        ["SMA", "SMa"],
                                        ["SL", "SL"],
                                        ["SP", "SP"],
                                        ["SM", "SM"],
                                        ["TR", "TR"],
                                        ["TK", "TK"],
                                        ["TB", "TB"],
                                        ["VR", "VR"],
                                        ["WP", "WP"],
                                        ["YS", "YS"],
                                        ["YG", "YG"],
                                        ["JB", "JB"],
                                        ["MKI", "MKi"]
                                    ],
                            "BLOCK" : [
                                       ["1BSA_01TRITON-X100",  "1% BSA; 0.1% Triton-X100"],
                                    ],
                            "CLASS" : [
                                ["IGM", "IgM"],
                                ["IGG1",    "IgG1"],
                                ["IGG2",    "IgG2"]
                                    ],
                            "COMPANY" : [
                                    ["ABCAM", "abcam"],
                                    ["CELL_SIGNALING", "cell signaling"],
                                    ["STRATAGEN", "stratagene"],
                                    ["CLONTECH", "clontech"],
                                    ["UBI", "ubi"],
                                    ["SOUTHERN_BIOTECH", "southern biotech"],
                                    ["PIERCE", "pierce"],
                                    ["PHARMIGEN", "pharmingen"],
                                    ["MOLECULAR_PROBES", "molecular probes"],
                                    ["PHARMACIA", "pharmacia"],
                                    ["BIORAD", "biorad"],
                                    ["EUROGENETIC", "eurogentec"],
                                    ["HOMEMADE", "homemade"],
                                    ["BD_BIOSCIENCE", "BD bioscience"],
                                    ["OBTAINED_FROM", "obtained from "],
                                    ["ZYMED", "Zymed"],
                                    ["UNKNOWN", "Unknown"],
                                    ["SANTA_CRUZ", "Santa Cruz"],
                                    ["BIOLEGEND", "Biolegend"],
                                    ["BETHYL", "Bethyl"],
                                    ["UPSTATE", "Upstate"],
                                    ["ROCKLAND", "Rockland"],
                                    ["NOVUS_BIOLOGICALS", "Novus Biologicals"],
                                    ["CHEMICON_INTERNATIONAL", "Chemicon International"],
                                    ["SIGMA", "Sigma"],
                                    ["ALPHA_DIAGNOSTIC_INTERNATIONAL", "Alpha Diagnostic International"],
                                    ["MILLIPORE", "Millipore"],
                                    ["ACTIVE_MOTIF", "Active motif"],
                                    ["NEB", "NEB"],
                                    ["NEOMARKERS", "Neomarkers"],
                                    ["LUBIOSCIENCE", "LubioScience"],
                                    ["EBIOSCIENCE", "eBioscience"],
                                    ["INVITROGEN", "Invitrogen"],
                                    ["STRESSGEN", "Stressgen"],
                                    ["COVANCE", "Covance"],
                                    ["ENZO_LIFE_SCIENCES", "Enzo Life Sciences"],
                                    ["CALBIOCHEM", "Calbiochem"],
                                    ["ROCHE", "Roche"],
                                    ["CYTOSKELETON", "Cytoskeleton"],
                                    ["OPEN_BIOSYSTEMS", "Open Biosystems"],
                                    ["BD_TRANSDUCTION", "BD Transduction"],
                                    ["ATLAS_ANTIBODIES_AB", "Atlas Antibodies AB"],
                                    ["GENENTECH", "Genentech"],
                                    ["TRANSDUCTION_LABS", "Transduction Labs"],
                                    ["ANTIBODIES_INCORPORATED", "Antibodies Incorporated"],
                                    ["BABCO", "BAbCO"],
                                    ["ERICH_NIGG_LAB_BASEL", "Erich Nigg lab (Basel)"],
                                    ["FRANCIS_BARR", "Francis Barr"],
                                    ["AVIVA_SYSTEMS_BIOLOGY", "Aviva Systems Biology"],
                                    ["LUCERNACHEM", "LucernaChem"],
                                    ["LI-COR", "LI-COR"],
                                    ["ABGENT", "Abgent"],
                                    ["CHROMOTEK", "Chromotek"],
                                    ["ABNOVA", "Abnova"],
                                    ["UNKNOWN", "Unknown"],
                                    ["ABSEA", "Absea"],
                                    ["GE_HEALTHCARE", "GE Healthcare"],
                                    ["GRAMSCH_LABORATORIES", "Gramsch Laboratories"],
                                    ["ADIPOGEN", "Adipogen"],
                                    ["COSMO_BIO_CO", "Cosmo bio co."],
                                    ["BECKTON_DICKINSON", "Beckton Dickinson"],
                                    ["BIOTIUM", "Biotium"]
                                    ],
                            "CONCENTRATION_FACS" : [
                                            ["1_TO_10", "1 : 10"],
                                            ["1_TO_20", "1 : 20"],
                                            ["1_TO_30", "1 : 30"],
                                            ["1_TO_40", "1 : 40"],
                                            ["1_TO_50", "1 : 50"],
                                            ["1_TO_100", "1 : 100"],
                                            ["1_TO_200", "1 : 200"],
                                            ["1_TO_500", "1 : 500"],
                                            ["1_TO_1000", "1 : 1000"],
                                            ["1_TO_2000", "1 : 2000"],
                                            ["1_TO_3000", "1 : 3000"],
                                            ["NOT_TESTED", "not tested"],
                                            ["NOT_WORKING", "not working"]
                                    ],
                            "CONCENTRATION_IP" : [
                                            ["1UL", "1 �l"],
                                            ["5UL", "5 �l"],
                                            ["10UL", "10 �l"],
                                            ["15UL", "15 �l"],
                                            ["20UL", "20 �l"],
                                            ["NOT_TESTED", "not tested"],
                                            ["NOT_WORKING", "not working"]
                                    ],
                            "CONCENTRATION_WESTERN" : [
                                                ["1_TO_100", "1 : 100"],
                                                ["1_TO_500", "1 : 500"],
                                                ["1_TO_1000", "1 : 1000"],
                                                ["1_TO_2000", "1 : 2000"],
                                                ["1_TO_3000", "1 : 3000"],
                                                ["1_TO_5000", "1 : 5000"],
                                                ["1_TO_10000", "1 : 10000"],
                                                ["1_TO_20000", "1 : 20000"],
                                                ["1_TO_25000", "1 : 25000"],
                                                ["NOT_TESTED", "not tested"],
                                                ["NOT_WORKING", "not working"]
                                    ],
                          "CURRENT_LAB_MEMBERS" : [
                                            ["CAROLINE_ZBINDEN", "Caroline Zbinden"],
                                            ["FRANK_VAN_DROGEN", "Frank Van Drogen"],
                                            ["INGRID_STOFFEL-STUDER", "Ingrid Stoffel-Studer"],
                                            ["MATTHIAS_PETER", "Matthias Peter"],
                                            ["REINHARD_DECHANT", "Reinhard Dechant"],
                                            ["WOJCIECH_PIWKO", "Wojciech Piwko"],
                                            ["JOCHEN_BECK", "Jochen Beck"]
                                    ],
                          "FIX" : [
                                ["1H-RT", "1h, RT"],
                                ["PTEMF", "PTEMF"],
                                ["PFA", "PFA"],
                                ["MEOH", "MeOH"]
                                    ],
                          "LABEL" : [
                                ["HRP", "hrp"],
                                ["AP", "ap"],
                                ["FITC", "fitc"],
                                ["CY3", "Cy3"],
                                ["ALEXA647", "Alexa 647"]
                                    ],
                          "ANTIBODY_LOCATION" : [
                                    ["SMALL_PETER_LAB", "Small Peter Lab"],
                                    ["BIG_PETER_LAB", "Big Peter Lab"],
                                    ["NEW_PETER_LAB", "New Peter Lab"],
                                    ["MINUS20_C-FLOOR", "-20C C-Floor"]
                                    ],
                          "MONO-POLYCLONAL" : [
                                            ["MONOCLONAL",  "Monoclonal"],
                                            ["POLYCLONAL",  "Polyclonal"],
                                            ["UNKNOWN", "Unknown"]
                                    ],
                          "SOURCE" : [
                                ["MOUSE",  "Mouse"],
                                ["RABBIT",  "Rabbit"],
                                ["HAMSTER",  "Hamster"],
                                ["GOAT",  "Goat"],
                                ["RAT",  "Rat"],
                                ["CHICKEN",  "Chicken"],
                                ["SHEEP",  "Sheep"],
                                ["HUMAN",  "Human"],
                                ["GUINEA_PIG",  "Guinea pig"],
                                ["DONEKY",  "Donkey"],
                                ["UNKNOWN",  "Unknown"]
                                    ],
                          "CELL_LOCATION" : [
                                ["FRIDGE",  "fridge"],
                                ["FREEZER",  "freezer"],
                                ["REFCO",  "refco"],
                                ["TANK",  "tank"]
                                    ],
                          "SELECTION" : [
                                ["NEOMYCIN_G418",  "Neomycin/G418"],
                                ["HYGROMYCIN",  "Hygromycin"],
                                ["MPA",  "MPA"],
                                ["G418",  "G418"],
                                ["PUROMYCIN",  "puromycin"],
                                ["BLASTICIDIN",  "Blasticidin"],
                                ["ZEOCIN",  "Zeocin"] 
                                    ],
                          "CO2" : [
                                ["5",  "5"],
                                ["7.5",  "7.5"]
                                    ],
                          "GROWTH_TEMPERATURE" : [
                                ["37",  "37"],
                                ["28",  "28"],
                                ["34",  "34"]
                                    ],
                          "MEDIUM" : [
                                ["RPMI1640",  "RPMI 1640"],
                                ["ISCOVES",  "Iscoves"],
                                ["DMEM",  "DMEM"],
                                ["LB",  "LB"],
                                ["DMEM_NUTRIENT",  "DMEM nutrient mixture F-12 HAM [D8437]"]
                                    ], 
                          "CELL_OBTAINED_FROM" : [
                                ["FREIBURG",  "Freiburg"],
                                ["ATCC",  "ATCC"],
                                ["DANIEL_GERLICH",  "Daniel Gerlich"],
                                ["ERICH_NIGG",  "Erich Nigg"],
                                ["KREK",  "Krek"],
                                ["TONY_HEYMAN",  "Tony Heyman"],
                                ["THOMAS-WILD_ULRIKE-KUTAY",  "Thomas Wild/Ulrike Kutay"],
                                ["JAN_MICHAEL_PETERS",  "Jan-Michael Peters"],
                                ["M_BRANDEIS",  "M Brandeis"],
                                ["ARI_HELENIUS",  "Ari Helenius"],
                                ["ROMEO_RICCI",  "Romeo Ricci"]
                                    ],  
                          "CELL_SPECIES" : [
                                ["HUMAN",  "human"],
                                ["MOUSE",  "mouse"],
                                ["RAT",  "rat"],
                                ["CHINESE_HAMSTER",  "chines hamster"],
                                ["HYBRIDOMA",  "hybridoma (human & mouse)"]                                
                                    ],  
                          "CONC_UNITS" : [
                                ["MICROG_MICROL",  "�g/�l"],
                                ["MG_ML",  "mgl/ml"],
                                ["UG_ML",  "ug/ml"]                               
                                    ],  
                          "OBTAINED_FROM" : [
                                ["F_CHANG", "F. Chang"],
                                ["J_CHANT", "J. Chant"],
                                ["R_DESHAIES", "R. Deshaies"],
                                ["E_ELION", "E. Elion"],
                                ["P_HIETER", "P. Hieter"],
                                ["I_HERSKOWITZ", "I. Herskowitz"],
                                ["A_NEIMAN", "A. Neiman"],
                                ["P_SORGER", "P. Sorger"],
                                ["T_STEARNS", "T. Stearns"],
                                ["MARC_BONDEL", "Marc Bondel"],
                                ["G_SUMARA", "G. Sumara"],
                                ["MICHAEL_ALTMANN", "Michael Altmann"],
                                ["HETEROZYGOUS_DIPLOID_COLLECTION", "Heterozygous diploid collection"],
                                ["ANNE-CHRISTINE_BUTTY", "Anne-Christine Butty"],
                                ["ANNE_PAQUELET", "Anne Paquelet"],
                                ["YAGMUR-TURGAY_KUTAY-GROUP", "Yagmur Turgay - Kutay group"],
                                ["BARBAR_CATARIN", "Barbar Catarin"],
                                ["FRANK_VAN-DROGEN", "Frank van Drogen"],
                                ["HEMMO_MEYER", "Hemmo Meyer"],
                                ["JEAN-MARC_GALLAND", "Jean-Marc Galland"],
                                ["JEFF_PARVIN", "Jeff Parvin"],
                                ["MARIE-PIERRE_GULLI", "Marie-Pierre Gulli"],
                                ["MIKIKO_TAKAHASHI", "Mikiko Takahashi"],
                                ["SANDRA_HENCHOZ", "Sandra Henchoz"],
                                ["MALIKA_JAQUENOUD", "Malika Jaquenoud"],
                                ["GERDA_JORRITSMA", "Gerda Jorritsma"],
                                ["CELINE_LAFOURCADE", "Céline Lafourcade"],
                                ["CELINE_LONGARETTI", "Céline Longaretti"],
                                ["BRIAN_LUKE", "Brian Luke"],
                                ["GUY_NIEDERHAUSER", "Guy Niederhäuser"],
                                ["NICOLAS_PAGE", "Nicolas Pag�"],
                                ["NATHALIE_PERRINJAQUET", "Nathalie Perrinjaquet"],
                                ["MATTHIAS_PETER", "Matthias Peter"],
                                ["AUDREY_PETIT", "Audrey Petit"],
                                ["LIONEL_PINTARD", "Lionel Pintard"],
                                ["YUKIKO_SHIMADA", "Yukiko Shimada"],
                                ["PHILIPPE_WIGET", "Philippe Wiget"],
                                ["VOLKER_STUCKE", "Volker Stucke"],
                                ["KATRIN_PETER", "Katrin Peter"],
                                ["MARC_BLONDEL", "marc blondel"],
                                ["M_FUNK", "M. Funk"],
                                ["ATTILA_BECSKEI", "Attila Becskei"],
                                ["GWENAEL_RABUT", "Gwenael Rabut"],
                                ["PHILIP_JERMANN", "Philip Jermann"],
                                ["P_PRYCIAK", "P.Pryciak"],
                                ["LINDA_HICKE", "Linda Hicke"],
                                ["RZPD", "RZPD"],
                                ["OPENBIO", "OpenBio"],
                                ["F_POSAS", "F. Posas"],
                                ["HAPLOID_COLLECTION", "Haploid collection"],
                                ["MIRIAM_BORTFELD", "Miriam Bortfeld"],
                                ["EUROSCARF", "Euroscarf"],
                                ["TS_COLLECTION", "ts collection"],
                                ["CONZELMANN_LAB", "Conzelmann lab"],
                                ["SEBASTIAN_LEIDEL", "Sebastian Leidel"],
                                ["ANNA_DEPLAZES", "Anna Deplazes"],
                                ["BIBOU", "Bibou"],
                                ["MARC_SOHRMANN", "Marc sohrmann"]
                                    ],
                          "SELECTION_YEAST" : [
                                ["NONE",  "None"],
                                ["URA",  "Ura"],
                                ["LEU",  "Leu"], 
                                ["TRP",  "Trp"], 
                                ["HIS",  "His"], 
                                ["VIABILITY",  "Viability"], 
                                ["NAT",  "nat"], 
                                ["KAN",  "kan"], 
                                ["KAN_NAT",  "kan + nat"], 
                                ["HIS_KAN",  "HIS + kan"], 
                                ["HIS_KAN_NAT",  "HIS + kan + nat"], 
                                ["HIS",  "HIS"], 
                                ["LEU_NAT",  "leu + nat"], 
                                ["ADE2",  "ade2"]
                                    ],  
                         "DERIVATION" : [
                                ["GAMMA_INTEG",  "gamma integ"],
                                ["DELTA_INTEG",  "� integ"],
                                ["5FAO_LOOPOUT",  "5-FAO loopout"],
                                ["PLASMID_SHUFFLE",  "plasmid shuffle"],
                                ["TETRAD",  "tetrad"],
                                ["LOOP-IN_LOOP-OUT",  "loop-in/loop-out"],
                                ["GALPHO",  "GalpHO mating type switch"],
                                ["DELETION",  "Deletion"],
                                ["INTEGRATION",  "Integration"]
                                    ],
                         "STRAIN_BACKGROUD" : [
                                ["W303",  "W303"],
                                ["K699",  "K699"],
                                ["K700",  "K700"],
                                ["S288C",  "S288C"],
                                ["1278",  "*1278*"],
                                ["EG123",  "EG123"],
                                ["DF5",  "DF5"],
                                ["SIGMA",  "Sigma"],
                                ["UNKNOWN",  "Don't know"],
                                ["BY7092",  "BY7092"],
                                ["BY5565",  "BY5565"],
                                ["BY4741",  "BY4741"]
                                    ],
                        "CIR" : [
                                ["CIR_PLUS",  "cir+"],
                                ["CIR_DEG",  "cir�"],
                                    ],
                        "GAL" : [
                                ["PLUS",  "Plus"],
                                ["PLUS_PLUS",  "Plus/Plus"],
                                ["GAL1",  "gal1"],
                                ["GAL1_GAL1",  "gal1/gal1"],      
                                ["GAL2",  "gal2"],                                 
                                ["GAL2_GAL2",  "gal2/gal2"],                                                         
                                    ],
                        "MAT" : [
                                ["AT",  "@"],
                                ["A",  "a"],
                                ["ALPHA",  "alpha"],
                                ["DIPLOID",  "diploid"],      
                                ["UNKNOWN",  "unknown"]                                                      
                                    ],
                        "FREEZER" : [
                                ["G9_FRIDGE-1",  "G9 Fridge 1"],
                                ["G9_FRIDGE-2",  "G9 Fridge 2"],
                                ["G9_FREEZER-A",  "-20 Small Peter Lab"],
                                ["G9_FREEZER-B",  "G9 Freezer B"],
                                ["G9_FREEZER-C",  "G9 Freezer C"],
                                ["G10_FREEZER-D",  "G10 Freezer D"],
                                ["G10_FREEZER-E",  "G10 Freezer E"],
                                ["G10_FREEZER-F",  "G10 Freezer F"],
                                ["G10_FREEZER-G",  "G10 Freezer G"],
                                ["G10_FREEZER-H",  "G10 Freezer H"],
                                ["G10_FREEZER-I",  "G10 Freezer I"],
                                ["G10_FRIDGE-3",  "+4C Big Peter Lab"],
                                ["G10_FRIDGE-4",  "G10 Fridge 4"],
                                ["G10_FRIDGE-5",  "G10 Fridge 5"],
                                ["G10_FRIDGE-6",  "G10 Fridge 6"],
                                ["G10_FRIDGE-7",  "G10 Fridge 7"],
                                ["G11_FRIDGE-8",  "G10 Fridge 8"],
                                ["G14_FREEZER-J",  "G14 Freezer J"],
                                ["G14_FREEZER-K",  "G14 Freezer K"],
                                ["G14_FREEZER-L",  "G14 Freezer L"],
                                ["G14_FREEZER-M",  "G14 Freezer M"],
                                ["G14_FRIDGE-9",  "G14 Fridge 9"],
                                ["G14_FRIDGE-10",  "G14 Fridge 10"],
                                ["G17_FRIDGE-11",  "G17 Fridge 11"],
                                ["G17_FRIDGE-12",  "G17 Fridge 12"],
                                ["G17_FREEZER-N",  "G17 Freezer N"],
                                ["USER_BENCH-20",  "Bench -20�C"],
                                ["USER_BENCH-80",  "Bench -80�C"],
                                ["USER_BENCH-RT",  "Bench RT"],
                                ["USER_BENCH",  "Bench"]
                                    ]
                          }