GRANT SELECT ON TABLE DATABASE_VERSION_LOGS TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE CHIP_CHIP_DATA TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE chip_chip_data_id_seq TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE DATA_SETS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE data_sets_id_seq TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE EVENTS TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE TIME_SERIES TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE time_series_id_seq TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE time_series_value_group_id_seq TO GROUP basysbio_readonly;

GRANT ALL ON TABLE DATABASE_VERSION_LOGS TO GROUP basysbio_readwrite;
GRANT ALL ON TABLE CHIP_CHIP_DATA TO GROUP basysbio_readwrite;
GRANT ALL ON SEQUENCE chip_chip_data_id_seq TO GROUP basysbio_readwrite;
GRANT ALL ON TABLE DATA_SETS TO GROUP basysbio_readwrite;
GRANT ALL ON SEQUENCE data_sets_id_seq TO GROUP basysbio_readwrite;
GRANT ALL ON TABLE EVENTS TO GROUP basysbio_readwrite;
GRANT ALL ON TABLE TIME_SERIES TO GROUP basysbio_readwrite;
GRANT ALL ON SEQUENCE time_series_id_seq TO GROUP basysbio_readwrite;
GRANT ALL ON SEQUENCE time_series_value_group_id_seq TO GROUP basysbio_readwrite;
