GRANT SELECT ON TABLE DATABASE_VERSION_LOGS TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE DATA_COLUMN_VALUES TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE SAMPLES TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE DATA_SETS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE DATA_SETS_ID_SEQ TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE EXPERIMENTS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE EXPERIMENTS_ID_SEQ TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE EVENTS TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE COLUMNS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE COLUMNS_ID_SEQ TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE DATA_COLUMNS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE DATA_COLUMNS_ID_SEQ TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE COLUMN_VALUES TO GROUP basysbio_readonly;
GRANT SELECT ON TABLE ROWS TO GROUP basysbio_readonly;
GRANT SELECT ON SEQUENCE ROWS_ID_SEQ TO GROUP basysbio_readonly;

GRANT ALL PRIVILEGES ON TABLE DATABASE_VERSION_LOGS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE DATA_COLUMN_VALUES TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE SAMPLES TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE DATA_SETS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON SEQUENCE DATA_SETS_ID_SEQ TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE EXPERIMENTS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON SEQUENCE EXPERIMENTS_ID_SEQ TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE EVENTS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE COLUMNS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON SEQUENCE COLUMNS_ID_SEQ TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE DATA_COLUMNS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON SEQUENCE DATA_COLUMNS_ID_SEQ TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE COLUMN_VALUES TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON TABLE ROWS TO GROUP basysbio_readwrite;
GRANT ALL PRIVILEGES ON SEQUENCE ROWS_ID_SEQ TO GROUP basysbio_readwrite;


