--
-- Feature: Unique property values
-- is_unique boolean_char DEFAULT false NOT NULL,

-- Columns used to store information regarding what properties should have unique values.

ALTER TABLE SAMPLE_TYPE_PROPERTY_TYPES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE EXPERIMENT_TYPE_PROPERTY_TYPES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE DATA_SET_TYPE_PROPERTY_TYPES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE MATERIAL_TYPE_PROPERTY_TYPES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;

ALTER TABLE SAMPLE_PROPERTIES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE EXPERIMENT_PROPERTIES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE DATA_SET_PROPERTIES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;
ALTER TABLE MATERIAL_PROPERTIES ADD COLUMN IS_UNIQUE BOOLEAN_CHAR NOT NULL DEFAULT FALSE;

-- These references exist to ensure referential integrity when modifying the database directly, they add some overhead to insert operations.
ALTER TABLE SAMPLE_TYPE_PROPERTY_TYPES ADD CONSTRAINT SAMPLE_TYPE_PROPERTY_TYPES_UNIQUE UNIQUE (ID, IS_UNIQUE);
ALTER TABLE EXPERIMENT_TYPE_PROPERTY_TYPES ADD CONSTRAINT EXPERIMENT_TYPE_PROPERTY_TYPES_UNIQUE UNIQUE (ID, IS_UNIQUE);
ALTER TABLE DATA_SET_TYPE_PROPERTY_TYPES ADD CONSTRAINT DATA_SET_TYPE_PROPERTY_TYPES_UNIQUE UNIQUE (ID, IS_UNIQUE);
ALTER TABLE MATERIAL_TYPE_PROPERTY_TYPES ADD CONSTRAINT MATERIAL_TYPE_PROPERTY_TYPES_UNIQUE UNIQUE (ID, IS_UNIQUE);

ALTER TABLE SAMPLE_PROPERTIES ADD CONSTRAINT SAMPLE_PROPERTIES_UNIQUE_FK FOREIGN KEY (STPT_ID, IS_UNIQUE) REFERENCES SAMPLE_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE);
ALTER TABLE EXPERIMENT_PROPERTIES ADD CONSTRAINT EXPERIMENT_PROPERTIES_UNIQUE_FK FOREIGN KEY (ETPT_ID, IS_UNIQUE) REFERENCES EXPERIMENT_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE);
ALTER TABLE DATA_SET_PROPERTIES ADD CONSTRAINT DATA_SET_PROPERTIES_UNIQUE_FK FOREIGN KEY (DSTPT_ID, IS_UNIQUE) REFERENCES DATA_SET_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE);
ALTER TABLE MATERIAL_PROPERTIES ADD CONSTRAINT MATERIAL_PROPERTIES_UNIQUE_FK FOREIGN KEY (MTPT_ID, IS_UNIQUE) REFERENCES MATERIAL_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE);

-- These constraints ensure uniqueness only when is_unique is TRUE
CREATE UNIQUE INDEX SAMPLE_PROPERTIES_UNIQUE_VALUE ON SAMPLE_PROPERTIES (STPT_ID, VALUE, CVTE_ID, MATE_PROP_ID, SAMP_PROP_ID) WHERE IS_UNIQUE;
CREATE UNIQUE INDEX EXPERIMENT_PROPERTIES_UNIQUE_VALUE ON EXPERIMENT_PROPERTIES (ETPT_ID, VALUE, CVTE_ID, MATE_PROP_ID, SAMP_PROP_ID) WHERE IS_UNIQUE;
CREATE UNIQUE INDEX DATA_SET_PROPERTIES_UNIQUE_VALUE ON DATA_SET_PROPERTIES (DSTPT_ID, VALUE, CVTE_ID, MATE_PROP_ID, SAMP_PROP_ID) WHERE IS_UNIQUE;
CREATE UNIQUE INDEX MATERIAL_PROPERTIES_UNIQUE_VALUE ON MATERIAL_PROPERTIES (MTPT_ID, VALUE, CVTE_ID, MATE_PROP_ID) WHERE IS_UNIQUE;