-- Migration from 118 to 119
-- 

-- Extend Sample Type
--

ALTER TABLE SAMPLE_TYPES ADD COLUMN SHOW_PARENT_METADATA BOOLEAN_CHAR NOT NULL DEFAULT 'F';

-- New sequencer for sample and experiment codes
--

CREATE SEQUENCE EXPERIMENT_CODE_SEQ; 
SELECT setval('EXPERIMENT_CODE_SEQ', nextval('CODE_SEQ'));
CREATE SEQUENCE SAMPLE_CODE_SEQ; 
SELECT setval('SAMPLE_CODE_SEQ', nextval('CODE_SEQ'));
GRANT SELECT ON SEQUENCE EXPERIMENT_CODE_SEQ TO GROUP OPENBIS_READONLY;
GRANT SELECT ON SEQUENCE SAMPLE_CODE_SEQ TO GROUP OPENBIS_READONLY;


