-- Migration from 063 to 064

-- Add SCRIPT_TYPE column to SCRIPTS
CREATE DOMAIN script_type AS VARCHAR(40) CHECK (VALUE IN ('DYNAMIC_PROPERTY', 'MANAGED_PROPERTY'));
ALTER TABLE scripts ADD COLUMN script_type script_type DEFAULT 'DYNAMIC_PROPERTY'; -- temporary default
UPDATE scripts SET script_type = 'DYNAMIC_PROPERTY';
ALTER TABLE SCRIPTS ALTER COLUMN SCRIPT_TYPE SET NOT NULL; 

