-- Migration from 071 to 072
UPDATE EXTERNAL_DATA SET SPEED_HINT=-50 where SPEED_HINT IS NULL;
ALTER TABLE EXTERNAL_DATA ALTER COLUMN SPEED_HINT SET DEFAULT -50;
ALTER TABLE EXTERNAL_DATA ALTER COLUMN SPEED_HINT SET NOT NULL;
