-- Longer descriptions
ALTER TABLE sample_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE data_set_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE experiment_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE material_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE controlled_vocabularies ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE data_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE file_format_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE locator_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE property_types ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE events ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE events ALTER COLUMN reason TYPE DESCRIPTION_1000;
ALTER TABLE groups ALTER COLUMN description TYPE DESCRIPTION_1000;
ALTER TABLE invalidations ALTER COLUMN reason TYPE DESCRIPTION_1000;


DROP TYPE DESCRIPTION_250;

-- Add label and description to controlled vocabularies

ALTER TABLE CONTROLLED_VOCABULARY_TERMS ADD COLUMN label COLUMN_LABEL;
ALTER TABLE CONTROLLED_VOCABULARY_TERMS ADD COLUMN description DESCRIPTION_1000;
