-- state domain
CREATE DOMAIN OPERATION_EXECUTION_STATE AS VARCHAR(40) CHECK (VALUE IN ('NEW', 'SCHEDULED', 'RUNNING', 'FINISHED', 'FAILED'));

-- table
CREATE TABLE OPERATION_EXECUTIONS (ID TECH_ID NOT NULL, CODE CODE NOT NULL, STATE OPERATION_EXECUTION_STATE NOT NULL, DESCRIPTION TEXT_VALUE NOT NULL, ERROR TEXT_VALUE, CREATION_DATE TIME_STAMP_DFL, START_DATE TIME_STAMP, FINISH_DATE TIME_STAMP);

-- sequence
CREATE SEQUENCE OPERATION_EXECUTIONS_ID_SEQ;

-- pk
ALTER TABLE OPERATION_EXECUTIONS ADD CONSTRAINT OPERATION_EXECUTIONS_PK PRIMARY KEY(ID);

-- code unique constraint
ALTER TABLE OPERATION_EXECUTIONS ADD CONSTRAINT OPERATION_EXECUTIONS_CODE_UK UNIQUE (CODE);

-- code index 
CREATE INDEX OPERATION_EXECUTIONS_CODE_I ON OPERATION_EXECUTIONS (CODE);

-- state and error check
ALTER TABLE OPERATION_EXECUTIONS ADD CONSTRAINT OPERATION_EXECUTIONS_STATE_ERROR_CHECK CHECK (STATE = 'FAILED' OR ERROR IS NULL);

-- grant
GRANT SELECT ON TABLE OPERATION_EXECUTIONS TO GROUP OPENBIS_READONLY;
