-- Project space relationship
DROP TRIGGER IF EXISTS ADD_PROJECT_TO_SPACE_CHECK ON PROJECTS;
CREATE TRIGGER ADD_PROJECT_TO_SPACE_CHECK AFTER INSERT ON PROJECTS
    FOR EACH ROW WHEN (NEW.SPACE_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_SPACE_RELATIONSHIP('project');

-- Experiment project relationship
DROP TRIGGER IF EXISTS ADD_EXPERIMENT_TO_PROJECT_CHECK ON EXPERIMENTS_ALL;
CREATE TRIGGER ADD_EXPERIMENT_TO_PROJECT_CHECK AFTER INSERT ON EXPERIMENTS_ALL
    FOR EACH ROW WHEN (NEW.PROJ_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_PROJECT_RELATIONSHIP('experiment');

-- Sample container setting and removing
DROP TRIGGER IF EXISTS ADD_SAMPLE_TO_CONTAINER_CHECK ON SAMPLES_ALL;
CREATE TRIGGER ADD_SAMPLE_TO_CONTAINER_CHECK AFTER INSERT ON SAMPLES_ALL
    FOR EACH ROW WHEN (NEW.CONT_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_SAMPLE_CONTAINER_RELATIONSHIP();

-- Sample experiment relationship
DROP TRIGGER IF EXISTS ADD_SAMPLE_TO_EXPERIMENT_CHECK ON SAMPLES_ALL;
CREATE TRIGGER ADD_SAMPLE_TO_EXPERIMENT_CHECK AFTER INSERT ON SAMPLES_ALL
    FOR EACH ROW WHEN (NEW.EXPE_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_EXPERIMENT_RELATIONSHIP('sample');

-- Sample project relationship
DROP TRIGGER IF EXISTS ADD_SAMPLE_TO_PROJECT_CHECK ON SAMPLES_ALL;
CREATE TRIGGER ADD_SAMPLE_TO_PROJECT_CHECK AFTER INSERT ON SAMPLES_ALL
    FOR EACH ROW WHEN (NEW.PROJ_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_PROJECT_RELATIONSHIP('sample');

-- Sample space relationship
DROP TRIGGER IF EXISTS ADD_SAMPLE_TO_SPACE_CHECK ON SAMPLES_ALL;
CREATE TRIGGER ADD_SAMPLE_TO_SPACE_CHECK AFTER INSERT ON SAMPLES_ALL
    FOR EACH ROW WHEN (NEW.SPACE_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_SPACE_RELATIONSHIP('sample');

-- Data set experiment relationship
DROP TRIGGER IF EXISTS ADD_DATA_SET_TO_EXPERIMENT_CHECK ON DATA_ALL;
CREATE TRIGGER ADD_DATA_SET_TO_EXPERIMENT_CHECK AFTER INSERT ON DATA_ALL
    FOR EACH ROW WHEN (NEW.EXPE_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_EXPERIMENT_RELATIONSHIP('data set');

-- Data set sample relationship
DROP TRIGGER IF EXISTS ADD_DATA_SET_TO_SAMPLE_CHECK ON DATA_ALL;
CREATE TRIGGER ADD_DATA_SET_TO_SAMPLE_CHECK AFTER INSERT ON DATA_ALL
    FOR EACH ROW WHEN (NEW.SAMP_FROZEN)
    EXECUTE PROCEDURE RAISE_EXCEPTION_FROZEN_DATA_SET_SAMPLE_RELATIONSHIP();

-- Freezing events
ALTER DOMAIN event_type DROP CONSTRAINT event_type_check;
ALTER DOMAIN event_type ADD CONSTRAINT event_type_check CHECK (VALUE IN ('DELETION', 'MOVEMENT', 'FREEZING'));
CREATE INDEX EVNT_FR_ID_FK_I ON EVENTS (EVENT_TYPE, IDENTIFIERS) WHERE EVENT_TYPE = 'FREEZING';
