-- Migration from 079 to 080
ALTER TABLE EXPERIMENT_TYPE_PROPERTY_TYPES ADD COLUMN IS_SHOWN_EDIT BOOLEAN_CHAR NOT NULL DEFAULT 'T';
ALTER TABLE MATERIAL_TYPE_PROPERTY_TYPES ADD COLUMN IS_SHOWN_EDIT BOOLEAN_CHAR NOT NULL DEFAULT 'T';
ALTER TABLE SAMPLE_TYPE_PROPERTY_TYPES ADD COLUMN IS_SHOWN_EDIT BOOLEAN_CHAR NOT NULL DEFAULT 'T';
ALTER TABLE DATA_SET_TYPE_PROPERTY_TYPES ADD COLUMN IS_SHOWN_EDIT BOOLEAN_CHAR NOT NULL DEFAULT 'T';

UPDATE EXPERIMENT_TYPE_PROPERTY_TYPES SET IS_SHOWN_EDIT='F' WHERE script_id IS NOT NULL;
UPDATE MATERIAL_TYPE_PROPERTY_TYPES SET IS_SHOWN_EDIT='F' WHERE script_id IS NOT NULL;
UPDATE SAMPLE_TYPE_PROPERTY_TYPES SET IS_SHOWN_EDIT='F' WHERE script_id IS NOT NULL;
UPDATE DATA_SET_TYPE_PROPERTY_TYPES SET IS_SHOWN_EDIT='F' WHERE script_id IS NOT NULL;
