-- Migration from 101 to 102

ALTER TABLE DATA_SET_RELATIONSHIPS_ALL DROP CONSTRAINT DSRE_DATA_FK_CHILD;
ALTER TABLE DATA_SET_RELATIONSHIPS_ALL DROP CONSTRAINT DSRE_DATA_FK_PARENT;

ALTER TABLE DATA_SET_RELATIONSHIPS_ALL ADD CONSTRAINT DSRE_DATA_FK_CHILD FOREIGN KEY (DATA_ID_CHILD) REFERENCES DATA_ALL(ID) ON DELETE CASCADE;
ALTER TABLE DATA_SET_RELATIONSHIPS_ALL ADD CONSTRAINT DSRE_DATA_FK_PARENT FOREIGN KEY (DATA_ID_PARENT) REFERENCES DATA_ALL(ID) ON DELETE CASCADE;
