-- Migration from 063 to 064

-- Add SCRIPT_TYPE column to SCRIPTS
CREATE DOMAIN SCRIPT_TYPE AS VARCHAR(40) CHECK (VALUE IN ('DYNAMIC_PROPERTY', 'MANAGED_PROPERTY'));
ALTER TABLE SCRIPTS ADD COLUMN SCRIPT_TYPE SCRIPT_TYPE;
UPDATE SCRIPTS SET SCRIPT_TYPE = 'DYNAMIC_PROPERTY';
ALTER TABLE SCRIPTS ALTER COLUMN SCRIPT_TYPE SET NOT NULL; 

