-- Migration from 104 to 105
ALTER DOMAIN DATA_STORE_SERVICE_REPORTING_PLUGIN_TYPE DROP CONSTRAINT DATA_STORE_SERVICE_REPORTING_PLUGIN_TYPE_CHECK;
ALTER DOMAIN DATA_STORE_SERVICE_REPORTING_PLUGIN_TYPE ADD CONSTRAINT DATA_STORE_SERVICE_REPORTING_PLUGIN_TYPE_CHECK CHECK (VALUE IN ('TABLE_MODEL', 'DSS_LINK', 'AGGREGATION_TABLE_MODEL'));