-- Migration from 067 to 068
ALTER DOMAIN ARCHIVING_STATUS DROP CONSTRAINT ARCHIVING_STATUS_CHECK;
ALTER DOMAIN ARCHIVING_STATUS ADD CONSTRAINT ARCHIVING_STATUS_CHECK CHECK (VALUE IN ('LOCKED', 'AVAILABLE', 'ARCHIVED', 'ARCHIVE_PENDING', 'UNARCHIVE_PENDING', 'BACKUP_PENDING'));


