-- Migration from 136 to 137

-- change FILE_NAME domain to VARCHAR(255), unfortunately a type cannot be altered for an existing domain

ALTER TABLE ATTACHMENTS ALTER COLUMN FILE_NAME TYPE VARCHAR(255);

DROP DOMAIN FILE_NAME;
CREATE DOMAIN FILE_NAME AS VARCHAR(255);

ALTER TABLE ATTACHMENTS ALTER COLUMN FILE_NAME TYPE FILE_NAME;
