ALTER TABLE external_data ADD COLUMN h5_folders BOOLEAN_CHAR NOT NULL DEFAULT 'T';
ALTER TABLE external_data ADD COLUMN h5ar_folders BOOLEAN_CHAR NOT NULL DEFAULT 'T';

ALTER TABLE external_data ALTER COLUMN h5_folders DROP DEFAULT;
ALTER TABLE external_data ALTER COLUMN h5ar_folders DROP DEFAULT;
