-- Migration from 185 to 186

CREATE TABLE EVENTS_SEARCH (
    ID TECH_ID NOT NULL,
    EVENT_TYPE EVENT_TYPE NOT NULL,
    ENTITY_TYPE TEXT_VALUE NOT NULL,
    ENTITY_SPACE TEXT_VALUE,
    ENTITY_SPACE_PERM_ID TEXT_VALUE,
    ENTITY_PROJECT TEXT_VALUE,
    ENTITY_PROJECT_PERM_ID TEXT_VALUE,
    ENTITY_REGISTERER TEXT_VALUE,
    ENTITY_REGISTRATION_TIMESTAMP TIME_STAMP,
    IDENTIFIER TEXT_VALUE NOT NULL,
    DESCRIPTION TEXT_VALUE,
    REASON TEXT_VALUE,
    CONTENT TEXT_VALUE,
    EXAC_ID TECH_ID,
    PERS_ID_REGISTERER TECH_ID NOT NULL,
    REGISTRATION_TIMESTAMP TIME_STAMP NOT NULL
);

-- pk
ALTER TABLE EVENTS_SEARCH ADD CONSTRAINT EVENTS_SEARCH_PK PRIMARY KEY(ID);

-- fk
ALTER TABLE EVENTS_SEARCH ADD CONSTRAINT EVENTS_SEARCH_PERS_ID_REGISTERER_FK FOREIGN KEY (PERS_ID_REGISTERER) REFERENCES PERSONS(ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EVENTS_SEARCH ADD CONSTRAINT EVENTS_SEARCH_EXAC_ID_FK FOREIGN KEY (EXAC_ID) REFERENCES ATTACHMENT_CONTENTS(ID);

-- constraint
ALTER TABLE EVENTS_SEARCH ADD CONSTRAINT EVENTS_SEARCH_ENTITY_TYPE_CK CHECK
	(ENTITY_TYPE IN ('ATTACHMENT', 'DATASET', 'EXPERIMENT', 'SPACE', 'MATERIAL', 'PROJECT', 'PROPERTY_TYPE', 'SAMPLE', 'VOCABULARY', 'AUTHORIZATION_GROUP', 'METAPROJECT'));

-- index
CREATE INDEX EVENTS_SEARCH_ENTITY_SPACE_I ON EVENTS_SEARCH (ENTITY_SPACE);
CREATE INDEX EVENTS_SEARCH_ENTITY_SPACE_PERM_ID_I ON EVENTS_SEARCH (ENTITY_SPACE_PERM_ID);
CREATE INDEX EVENTS_SEARCH_ENTITY_PROJECT_I ON EVENTS_SEARCH (ENTITY_PROJECT);
CREATE INDEX EVENTS_SEARCH_ENTITY_PROJECT_PERM_ID_I ON EVENTS_SEARCH (ENTITY_PROJECT_PERM_ID);
CREATE INDEX EVENTS_SEARCH_ENTITY_REGISTERER_I ON EVENTS_SEARCH (ENTITY_REGISTERER);
CREATE INDEX EVENTS_SEARCH_ENTITY_REGISTRATION_TIMESTAMP_I ON EVENTS_SEARCH (ENTITY_REGISTRATION_TIMESTAMP);
CREATE INDEX EVENTS_SEARCH_PERS_ID_REGISTERER_I ON EVENTS_SEARCH (PERS_ID_REGISTERER);
CREATE INDEX EVENTS_SEARCH_REGISTRATION_TIMESTAMP_I ON EVENTS_SEARCH (REGISTRATION_TIMESTAMP);
CREATE INDEX EVENTS_SEARCH_EXAC_ID_I ON EVENTS_SEARCH (EXAC_ID);

-- sequence
CREATE SEQUENCE EVENTS_SEARCH_ID_SEQ;

-- grants
GRANT SELECT ON SEQUENCE EVENTS_SEARCH_ID_SEQ TO GROUP OPENBIS_READONLY;
GRANT SELECT ON TABLE EVENTS_SEARCH TO GROUP OPENBIS_READONLY;
