-- Migration from 070 to 071
ALTER TABLE CONTROLLED_VOCABULARY_TERMS ADD COLUMN IS_OFFICIAL BOOLEAN_CHAR NOT NULL DEFAULT 'T';

-- 
-- Virtual data set related changes
--
ALTER TABLE DATA ADD COLUMN IS_VIRTUAL BOOLEAN_CHAR DEFAULT false;
ALTER TABLE DATA ADD COLUMN VIRT_ORDER INTEGER;
ALTER TABLE DATA ADD COLUMN VIRT_PARENT_ID TECH_ID DEFAULT NULL;
ALTER TABLE DATA ADD CONSTRAINT DATA_VIRT_PARENT_FK FOREIGN KEY (VIRT_PARENT_ID) REFERENCES DATA(ID);

