-- Remove ID column from SAMPLE_INPUTS table
DROP SEQUENCE SAMPLE_INPUT_ID_SEQ;
ALTER TABLE SAMPLE_INPUTS DROP CONSTRAINT SAIN_PK;
ALTER TABLE SAMPLE_INPUTS DROP COLUMN ID;
ALTER TABLE SAMPLE_INPUTS ADD CONSTRAINT SAIN_PK PRIMARY KEY(SAMP_ID,PROC_ID);

-- Remove ID and REGISTRATION_TIMESTAMP column from DATA_SET_RELATIONSHIPS table
DROP SEQUENCE DATA_SET_RELATIONSHIP_ID_SEQ;
ALTER TABLE DATA_SET_RELATIONSHIPS DROP CONSTRAINT DSRE_PK;
ALTER TABLE DATA_SET_RELATIONSHIPS DROP CONSTRAINT DSRE_BK_UK;
ALTER TABLE DATA_SET_RELATIONSHIPS DROP COLUMN ID;
ALTER TABLE DATA_SET_RELATIONSHIPS DROP COLUMN REGISTRATION_TIMESTAMP;
ALTER TABLE DATA_SET_RELATIONSHIPS ADD CONSTRAINT DSRE_PK PRIMARY KEY(DATA_ID_PARENT,DATA_ID_CHILD);
