DROP TRIGGER IF EXISTS LINK_DATA_SET_FROZEN_CHECK_ON_INSERT ON CONTENT_COPIES;
DROP TRIGGER IF EXISTS LINK_DATA_SET_FROZEN_CHECK_ON_DELETE ON CONTENT_COPIES;
DROP FUNCTION IF EXISTS RAISE_EXCEPTION_FROZEN_LINK_DATA_SET();