ALTER TABLE EVENTS ADD COLUMN EXAC_ID TECH_ID;
ALTER TABLE EVENTS ADD CONSTRAINT EVNT_EXAC_FK FOREIGN KEY (EXAC_ID) REFERENCES ATTACHMENT_CONTENTS(ID);
CREATE INDEX evnt_exac_fk_i ON events USING btree (exac_id);


