-- Migration from 135 to 136

-- drop project FKs
ALTER TABLE EXPERIMENTS_ALL DROP CONSTRAINT IF EXISTS EXPE_PROJ_FK;
ALTER TABLE ATTACHMENTS DROP CONSTRAINT IF EXISTS ATTA_PROJ_FK;
ALTER TABLE EXPERIMENT_RELATIONSHIPS_HISTORY DROP CONSTRAINT IF EXISTS EXRELH_PROJ_FK;
ALTER TABLE PROJECT_RELATIONSHIPS_HISTORY DROP CONSTRAINT IF EXISTS PRRELH_MAIN_PROJ_FK;

-- drop space FKs
ALTER TABLE PERSONS DROP CONSTRAINT IF EXISTS PERS_SPACE_FK;
ALTER TABLE PROJECTS DROP CONSTRAINT IF EXISTS PROJ_SPACE_FK;
ALTER TABLE ROLE_ASSIGNMENTS DROP CONSTRAINT IF EXISTS ROAS_SPACE_FK;
ALTER TABLE SAMPLES_ALL DROP CONSTRAINT IF EXISTS SAMP_SPACE_FK;
ALTER TABLE SAMPLE_RELATIONSHIPS_HISTORY DROP CONSTRAINT IF EXISTS SAMPRELH_SPACE_FK;
ALTER TABLE PROJECT_RELATIONSHIPS_HISTORY DROP CONSTRAINT IF EXISTS PRRELH_SPACE_FK;

-- create deferrable project FKs
ALTER TABLE EXPERIMENTS_ALL ADD CONSTRAINT EXPE_PROJ_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECTS(ID)  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ATTACHMENTS ADD CONSTRAINT ATTA_PROJ_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECTS(ID)  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EXPERIMENT_RELATIONSHIPS_HISTORY ADD CONSTRAINT EXRELH_PROJ_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECTS(ID) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PROJECT_RELATIONSHIPS_HISTORY ADD CONSTRAINT PRRELH_MAIN_PROJ_FK FOREIGN KEY (MAIN_PROJ_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- create deferrable space FKs
ALTER TABLE PERSONS ADD CONSTRAINT PERS_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PROJECTS ADD CONSTRAINT PROJ_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ROLE_ASSIGNMENTS ADD CONSTRAINT ROAS_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SAMPLES_ALL ADD CONSTRAINT SAMP_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SAMPLE_RELATIONSHIPS_HISTORY ADD CONSTRAINT SAMPRELH_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PROJECT_RELATIONSHIPS_HISTORY ADD CONSTRAINT PRRELH_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACES(ID) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;


