-- Migration from 005 to 006

ALTER TABLE FEATURE_DEFS ADD COLUMN CODE NAME;

UPDATE FEATURE_DEFS SET CODE = regexp_replace(upper(NAME), '[^A-Z0-9]', '_', 'g');

ALTER TABLE FEATURE_DEFS ALTER COLUMN CODE SET NOT NULL;
ALTER TABLE FEATURE_DEFS ADD CONSTRAINT FEATURE_DEFS_UK_2 UNIQUE(CODE, DS_ID);
