-- JAVA ch.systemsx.cisd.openbis.plugin.phosphonetx.server.dataaccess.db.migration.MigrationStepFrom002To003

ALTER TABLE IDENTIFIED_PROTEINS ADD COLUMN COVERAGE REAL_NUMBER;

CREATE TABLE PROTEIN_VIEW_CACHE (
    ID BIGSERIAL  NOT NULL,
    EXPERIMENT_PERM_ID CODE  NOT NULL,
    BLOB BYTEA NOT NULL,
    CONSTRAINT PK_PROTEIN_VIEW PRIMARY KEY (ID)
);

