import ch.systemsx.cisd.openbis.generic.server.jython.api.v1.DataType as DataType

tr = service.transaction()

''' VOCABULARIES '''

vocabulary_LICENSE = tr.getOrCreateNewVocabulary('LICENSE')
vocabulary_LICENSE.setChosenFromList(True)

vocabulary_term_LICENSE_NONE = tr.createNewVocabularyTerm('NONE')
vocabulary_term_LICENSE_NONE.setLabel('None')
vocabulary_term_LICENSE_NONE.setOrdinal(1)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_NONE)

vocabulary_term_LICENSE_CC_BY = tr.createNewVocabularyTerm('CC_BY')
vocabulary_term_LICENSE_CC_BY.setLabel('CC BY')
vocabulary_term_LICENSE_CC_BY.setOrdinal(2)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY)

vocabulary_term_LICENSE_CC_BY_SA = tr.createNewVocabularyTerm('CC_BY_SA')
vocabulary_term_LICENSE_CC_BY_SA.setLabel('CC BY-SA')
vocabulary_term_LICENSE_CC_BY_SA.setOrdinal(3)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY_SA)

vocabulary_term_LICENSE_CC_BY_ND = tr.createNewVocabularyTerm('CC_BY_ND')
vocabulary_term_LICENSE_CC_BY_ND.setLabel('CC BY-ND')
vocabulary_term_LICENSE_CC_BY_ND.setOrdinal(4)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY_ND)

vocabulary_term_LICENSE_CC_BY_NC = tr.createNewVocabularyTerm('CC_BY_NC')
vocabulary_term_LICENSE_CC_BY_NC.setLabel('CC BY-NC')
vocabulary_term_LICENSE_CC_BY_NC.setOrdinal(5)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY_NC)

vocabulary_term_LICENSE_CC_BY_NC_SA = tr.createNewVocabularyTerm('CC_BY_NC_SA')
vocabulary_term_LICENSE_CC_BY_NC_SA.setLabel('CC BY-NC-SA')
vocabulary_term_LICENSE_CC_BY_NC_SA.setOrdinal(6)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY_NC_SA)

vocabulary_term_LICENSE_CC_BY_NC_ND = tr.createNewVocabularyTerm('CC_BY_NC_ND')
vocabulary_term_LICENSE_CC_BY_NC_ND.setLabel('CC BY-NC-ND')
vocabulary_term_LICENSE_CC_BY_NC_ND.setOrdinal(7)
vocabulary_LICENSE.addTerm(vocabulary_term_LICENSE_CC_BY_NC_ND)

''' ENTITY TYPES '''

experiment_type_PUBLICATION = tr.getOrCreateNewExperimentType('PUBLICATION')
experiment_type_PUBLICATION.setDescription(None)

dataset_type_PUBLICATION_CONTAINER = tr.getOrCreateNewDataSetType('PUBLICATION_CONTAINER')

''' PROPERTY TYPES '''

prop_type_PUBLICATION_ID = tr.getOrCreateNewPropertyType('PUBLICATION_ID', DataType.VARCHAR)
prop_type_PUBLICATION_ID.setLabel('Publication Id')
prop_type_PUBLICATION_ID.setManagedInternally(False)

prop_type_PUBLICATION_TITLE = tr.getOrCreateNewPropertyType('PUBLICATION_TITLE', DataType.VARCHAR)
prop_type_PUBLICATION_TITLE.setLabel('Title')
prop_type_PUBLICATION_TITLE.setManagedInternally(False)

prop_type_PUBLICATION_AUTHOR = tr.getOrCreateNewPropertyType('PUBLICATION_AUTHOR', DataType.VARCHAR)
prop_type_PUBLICATION_AUTHOR.setLabel('Author')
prop_type_PUBLICATION_AUTHOR.setManagedInternally(False)

prop_type_PUBLICATION_AUTHOR_EMAIL = tr.getOrCreateNewPropertyType('PUBLICATION_AUTHOR_EMAIL', DataType.VARCHAR)
prop_type_PUBLICATION_AUTHOR_EMAIL.setLabel('Author Email')
prop_type_PUBLICATION_AUTHOR_EMAIL.setManagedInternally(False)

prop_type_PUBLICATION_LICENSE = tr.getOrCreateNewPropertyType('PUBLICATION_LICENSE', DataType.CONTROLLEDVOCABULARY)
prop_type_PUBLICATION_LICENSE.setLabel('License')
prop_type_PUBLICATION_LICENSE.setVocabulary(vocabulary_LICENSE)
prop_type_PUBLICATION_LICENSE.setManagedInternally(False)

prop_type_PUBLICATION_NOTES = tr.getOrCreateNewPropertyType('PUBLICATION_NOTES', DataType.MULTILINE_VARCHAR)
prop_type_PUBLICATION_NOTES.setLabel('Notes')
prop_type_PUBLICATION_NOTES.setManagedInternally(False)

prop_type_PUBLICATION_MESH_TERMS = tr.getOrCreateNewPropertyType('PUBLICATION_MESH_TERMS', DataType.MULTILINE_VARCHAR)
prop_type_PUBLICATION_MESH_TERMS.setLabel('Mesh Terms')
prop_type_PUBLICATION_MESH_TERMS.setManagedInternally(False)

prop_type_PUBLICATION_MESH_TERMS_DATABASE = tr.getOrCreateNewPropertyType('PUBLICATION_MESH_TERMS_DATABASE', DataType.VARCHAR)
prop_type_PUBLICATION_MESH_TERMS_DATABASE.setLabel('Mesh Terms Database')
prop_type_PUBLICATION_MESH_TERMS_DATABASE.setManagedInternally(False)

prop_type_PUBLICATION_MAPPING = tr.getOrCreateNewPropertyType('PUBLICATION_MAPPING', DataType.VARCHAR)
prop_type_PUBLICATION_MAPPING.setLabel('Mapping')
prop_type_PUBLICATION_MAPPING.setManagedInternally(False)

''' PROPERTY ASSIGNMENTS '''

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_ID = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_ID)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_ID.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_ID.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_ID.setPositionInForms(10)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_TITLE = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_TITLE)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_TITLE.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_TITLE.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_TITLE.setPositionInForms(20)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_AUTHOR)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR.setPositionInForms(30)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR_EMAIL = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_AUTHOR_EMAIL)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR_EMAIL.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR_EMAIL.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR_EMAIL.setPositionInForms(40)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_NOTES = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_NOTES)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_NOTES.setMandatory(False)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_NOTES.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_NOTES.setPositionInForms(50)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_MESH_TERMS)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS.setPositionInForms(60)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS_DATABASE = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_MESH_TERMS_DATABASE)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS_DATABASE.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS_DATABASE.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS_DATABASE.setPositionInForms(70)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_LICENSE = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_LICENSE)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_LICENSE.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_LICENSE.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_LICENSE.setPositionInForms(80)

assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MAPPING = tr.assignPropertyType(experiment_type_PUBLICATION, prop_type_PUBLICATION_MAPPING)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MAPPING.setMandatory(True)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MAPPING.setSection(None)
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MAPPING.setPositionInForms(90)

''' DEFAULTS FOR EXISTING EXPERIMENTS (for development) '''
'''
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_ID.setDefaultValue("default id")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_TITLE.setDefaultValue("default title")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR.setDefaultValue("default author")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_AUTHOR_EMAIL.setDefaultValue("default@email.com")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_NOTES.setDefaultValue("default notes")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS.setDefaultValue("default mesh terms")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MESH_TERMS_DATABASE.setDefaultValue("default mesh terms database")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_LICENSE.setDefaultValue("NONE")
assignment_EXPERIMENT_PUBLICATION_PUBLICATION_MAPPING.setDefaultValue("{}")
'''