transaction = service.transaction(incoming, factory)
dataSet1 = transaction.createNewDataSet()
transaction.moveFile(incoming.getPath() + '/sub_data_set_1', dataSet1)
dataSet1.setDataSetType('O1')
dataSet1.setExperiment(transaction.getExperiment('/SPACE/PROJECT/EXP1'))
dataSet2 = transaction.createNewDataSet()
transaction.moveFile(incoming.getPath() + '/sub_data_set_2', dataSet2)
dataSet2.setDataSetType('O1')
dataSet2.setExperiment(transaction.getExperiment('/SPACE/PROJECT/EXP2'))

