-- change CODE domain to VARCHAR(60), unfortunately a type cannot be altered for an existing domain

ALTER TABLE DATA_SETS ALTER COLUMN CODE TYPE VARCHAR(60);

DROP DOMAIN CODE;
CREATE DOMAIN CODE AS VARCHAR(60);

ALTER TABLE DATA_SETS ALTER COLUMN CODE TYPE CODE;
